// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: answer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConceptDocument_Node_Leaf_Kind int32

const (
	ConceptDocument_Node_Leaf_Entity        ConceptDocument_Node_Leaf_Kind = 0
	ConceptDocument_Node_Leaf_Relation      ConceptDocument_Node_Leaf_Kind = 1
	ConceptDocument_Node_Leaf_AttributeKind ConceptDocument_Node_Leaf_Kind = 3 // Renamed to avoid conflict with Attribute message
	ConceptDocument_Node_Leaf_Role          ConceptDocument_Node_Leaf_Kind = 4
)

// Enum value maps for ConceptDocument_Node_Leaf_Kind.
var (
	ConceptDocument_Node_Leaf_Kind_name = map[int32]string{
		0: "Entity",
		1: "Relation",
		3: "AttributeKind",
		4: "Role",
	}
	ConceptDocument_Node_Leaf_Kind_value = map[string]int32{
		"Entity":        0,
		"Relation":      1,
		"AttributeKind": 3,
		"Role":          4,
	}
)

func (x ConceptDocument_Node_Leaf_Kind) Enum() *ConceptDocument_Node_Leaf_Kind {
	p := new(ConceptDocument_Node_Leaf_Kind)
	*p = x
	return p
}

func (x ConceptDocument_Node_Leaf_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConceptDocument_Node_Leaf_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_answer_proto_enumTypes[0].Descriptor()
}

func (ConceptDocument_Node_Leaf_Kind) Type() protoreflect.EnumType {
	return &file_answer_proto_enumTypes[0]
}

func (x ConceptDocument_Node_Leaf_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConceptDocument_Node_Leaf_Kind.Descriptor instead.
func (ConceptDocument_Node_Leaf_Kind) EnumDescriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2, 0, 2, 0}
}

type ConceptRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []*RowEntry            `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptRow) Reset() {
	*x = ConceptRow{}
	mi := &file_answer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptRow) ProtoMessage() {}

func (x *ConceptRow) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptRow.ProtoReflect.Descriptor instead.
func (*ConceptRow) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{0}
}

func (x *ConceptRow) GetRow() []*RowEntry {
	if x != nil {
		return x.Row
	}
	return nil
}

type RowEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entry:
	//
	//	*RowEntry_Empty_
	//	*RowEntry_Concept
	//	*RowEntry_Value
	//	*RowEntry_ConceptList_
	//	*RowEntry_ValueList_
	Entry         isRowEntry_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowEntry) Reset() {
	*x = RowEntry{}
	mi := &file_answer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowEntry) ProtoMessage() {}

func (x *RowEntry) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowEntry.ProtoReflect.Descriptor instead.
func (*RowEntry) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{1}
}

func (x *RowEntry) GetEntry() isRowEntry_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *RowEntry) GetEmpty() *RowEntry_Empty {
	if x != nil {
		if x, ok := x.Entry.(*RowEntry_Empty_); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *RowEntry) GetConcept() *Concept {
	if x != nil {
		if x, ok := x.Entry.(*RowEntry_Concept); ok {
			return x.Concept
		}
	}
	return nil
}

func (x *RowEntry) GetValue() *Value {
	if x != nil {
		if x, ok := x.Entry.(*RowEntry_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *RowEntry) GetConceptList() *RowEntry_ConceptList {
	if x != nil {
		if x, ok := x.Entry.(*RowEntry_ConceptList_); ok {
			return x.ConceptList
		}
	}
	return nil
}

func (x *RowEntry) GetValueList() *RowEntry_ValueList {
	if x != nil {
		if x, ok := x.Entry.(*RowEntry_ValueList_); ok {
			return x.ValueList
		}
	}
	return nil
}

type isRowEntry_Entry interface {
	isRowEntry_Entry()
}

type RowEntry_Empty_ struct {
	Empty *RowEntry_Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type RowEntry_Concept struct {
	Concept *Concept `protobuf:"bytes,2,opt,name=concept,proto3,oneof"`
}

type RowEntry_Value struct {
	Value *Value `protobuf:"bytes,3,opt,name=value,proto3,oneof"`
}

type RowEntry_ConceptList_ struct {
	ConceptList *RowEntry_ConceptList `protobuf:"bytes,4,opt,name=concept_list,json=conceptList,proto3,oneof"`
}

type RowEntry_ValueList_ struct {
	ValueList *RowEntry_ValueList `protobuf:"bytes,5,opt,name=value_list,json=valueList,proto3,oneof"`
}

func (*RowEntry_Empty_) isRowEntry_Entry() {}

func (*RowEntry_Concept) isRowEntry_Entry() {}

func (*RowEntry_Value) isRowEntry_Entry() {}

func (*RowEntry_ConceptList_) isRowEntry_Entry() {}

func (*RowEntry_ValueList_) isRowEntry_Entry() {}

type ConceptDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *ConceptDocument_Node  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptDocument) Reset() {
	*x = ConceptDocument{}
	mi := &file_answer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDocument) ProtoMessage() {}

func (x *ConceptDocument) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDocument.ProtoReflect.Descriptor instead.
func (*ConceptDocument) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2}
}

func (x *ConceptDocument) GetRoot() *ConceptDocument_Node {
	if x != nil {
		return x.Root
	}
	return nil
}

type RowEntry_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowEntry_Empty) Reset() {
	*x = RowEntry_Empty{}
	mi := &file_answer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowEntry_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowEntry_Empty) ProtoMessage() {}

func (x *RowEntry_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowEntry_Empty.ProtoReflect.Descriptor instead.
func (*RowEntry_Empty) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{1, 0}
}

type RowEntry_ConceptList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concepts      []*Concept             `protobuf:"bytes,1,rep,name=concepts,proto3" json:"concepts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowEntry_ConceptList) Reset() {
	*x = RowEntry_ConceptList{}
	mi := &file_answer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowEntry_ConceptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowEntry_ConceptList) ProtoMessage() {}

func (x *RowEntry_ConceptList) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowEntry_ConceptList.ProtoReflect.Descriptor instead.
func (*RowEntry_ConceptList) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RowEntry_ConceptList) GetConcepts() []*Concept {
	if x != nil {
		return x.Concepts
	}
	return nil
}

type RowEntry_ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowEntry_ValueList) Reset() {
	*x = RowEntry_ValueList{}
	mi := &file_answer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowEntry_ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowEntry_ValueList) ProtoMessage() {}

func (x *RowEntry_ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowEntry_ValueList.ProtoReflect.Descriptor instead.
func (*RowEntry_ValueList) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{1, 2}
}

func (x *RowEntry_ValueList) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConceptDocument_Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Node:
	//
	//	*ConceptDocument_Node_Map_
	//	*ConceptDocument_Node_List_
	//	*ConceptDocument_Node_Leaf_
	Node          isConceptDocument_Node_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptDocument_Node) Reset() {
	*x = ConceptDocument_Node{}
	mi := &file_answer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDocument_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDocument_Node) ProtoMessage() {}

func (x *ConceptDocument_Node) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDocument_Node.ProtoReflect.Descriptor instead.
func (*ConceptDocument_Node) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ConceptDocument_Node) GetNode() isConceptDocument_Node_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ConceptDocument_Node) GetMap() *ConceptDocument_Node_Map {
	if x != nil {
		if x, ok := x.Node.(*ConceptDocument_Node_Map_); ok {
			return x.Map
		}
	}
	return nil
}

func (x *ConceptDocument_Node) GetList() *ConceptDocument_Node_List {
	if x != nil {
		if x, ok := x.Node.(*ConceptDocument_Node_List_); ok {
			return x.List
		}
	}
	return nil
}

func (x *ConceptDocument_Node) GetLeaf() *ConceptDocument_Node_Leaf {
	if x != nil {
		if x, ok := x.Node.(*ConceptDocument_Node_Leaf_); ok {
			return x.Leaf
		}
	}
	return nil
}

type isConceptDocument_Node_Node interface {
	isConceptDocument_Node_Node()
}

type ConceptDocument_Node_Map_ struct {
	Map *ConceptDocument_Node_Map `protobuf:"bytes,1,opt,name=map,proto3,oneof"`
}

type ConceptDocument_Node_List_ struct {
	List *ConceptDocument_Node_List `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_ struct {
	Leaf *ConceptDocument_Node_Leaf `protobuf:"bytes,3,opt,name=leaf,proto3,oneof"`
}

func (*ConceptDocument_Node_Map_) isConceptDocument_Node_Node() {}

func (*ConceptDocument_Node_List_) isConceptDocument_Node_Node() {}

func (*ConceptDocument_Node_Leaf_) isConceptDocument_Node_Node() {}

type ConceptDocument_Node_Map struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Map           map[string]*ConceptDocument_Node `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptDocument_Node_Map) Reset() {
	*x = ConceptDocument_Node_Map{}
	mi := &file_answer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDocument_Node_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDocument_Node_Map) ProtoMessage() {}

func (x *ConceptDocument_Node_Map) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDocument_Node_Map.ProtoReflect.Descriptor instead.
func (*ConceptDocument_Node_Map) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ConceptDocument_Node_Map) GetMap() map[string]*ConceptDocument_Node {
	if x != nil {
		return x.Map
	}
	return nil
}

type ConceptDocument_Node_List struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	List          []*ConceptDocument_Node `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptDocument_Node_List) Reset() {
	*x = ConceptDocument_Node_List{}
	mi := &file_answer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDocument_Node_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDocument_Node_List) ProtoMessage() {}

func (x *ConceptDocument_Node_List) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDocument_Node_List.ProtoReflect.Descriptor instead.
func (*ConceptDocument_Node_List) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2, 0, 1}
}

func (x *ConceptDocument_Node_List) GetList() []*ConceptDocument_Node {
	if x != nil {
		return x.List
	}
	return nil
}

type ConceptDocument_Node_Leaf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Leaf:
	//
	//	*ConceptDocument_Node_Leaf_Empty_
	//	*ConceptDocument_Node_Leaf_EntityType
	//	*ConceptDocument_Node_Leaf_RelationType
	//	*ConceptDocument_Node_Leaf_AttributeType
	//	*ConceptDocument_Node_Leaf_RoleType
	//	*ConceptDocument_Node_Leaf_ValueType
	//	*ConceptDocument_Node_Leaf_Attribute
	//	*ConceptDocument_Node_Leaf_Value
	//	*ConceptDocument_Node_Leaf_Kind_
	Leaf          isConceptDocument_Node_Leaf_Leaf `protobuf_oneof:"leaf"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptDocument_Node_Leaf) Reset() {
	*x = ConceptDocument_Node_Leaf{}
	mi := &file_answer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDocument_Node_Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDocument_Node_Leaf) ProtoMessage() {}

func (x *ConceptDocument_Node_Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDocument_Node_Leaf.ProtoReflect.Descriptor instead.
func (*ConceptDocument_Node_Leaf) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2, 0, 2}
}

func (x *ConceptDocument_Node_Leaf) GetLeaf() isConceptDocument_Node_Leaf_Leaf {
	if x != nil {
		return x.Leaf
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetEmpty() *ConceptDocument_Node_Leaf_Empty {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_Empty_); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetEntityType() *EntityType {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_EntityType); ok {
			return x.EntityType
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetRelationType() *RelationType {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_RelationType); ok {
			return x.RelationType
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetAttributeType() *AttributeType {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_AttributeType); ok {
			return x.AttributeType
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetRoleType() *RoleType {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_RoleType); ok {
			return x.RoleType
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetValueType() *ValueType {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_ValueType); ok {
			return x.ValueType
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetAttribute() *Attribute {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_Attribute); ok {
			return x.Attribute
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetValue() *Value {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *ConceptDocument_Node_Leaf) GetKind() ConceptDocument_Node_Leaf_Kind {
	if x != nil {
		if x, ok := x.Leaf.(*ConceptDocument_Node_Leaf_Kind_); ok {
			return x.Kind
		}
	}
	return ConceptDocument_Node_Leaf_Entity
}

type isConceptDocument_Node_Leaf_Leaf interface {
	isConceptDocument_Node_Leaf_Leaf()
}

type ConceptDocument_Node_Leaf_Empty_ struct {
	Empty *ConceptDocument_Node_Leaf_Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_EntityType struct {
	EntityType *EntityType `protobuf:"bytes,10,opt,name=entity_type,json=entityType,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_RelationType struct {
	RelationType *RelationType `protobuf:"bytes,11,opt,name=relation_type,json=relationType,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_AttributeType struct {
	AttributeType *AttributeType `protobuf:"bytes,12,opt,name=attribute_type,json=attributeType,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_RoleType struct {
	RoleType *RoleType `protobuf:"bytes,13,opt,name=role_type,json=roleType,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_ValueType struct {
	ValueType *ValueType `protobuf:"bytes,15,opt,name=value_type,json=valueType,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_Attribute struct {
	Attribute *Attribute `protobuf:"bytes,20,opt,name=attribute,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_Value struct {
	Value *Value `protobuf:"bytes,21,opt,name=value,proto3,oneof"`
}

type ConceptDocument_Node_Leaf_Kind_ struct {
	Kind ConceptDocument_Node_Leaf_Kind `protobuf:"varint,30,opt,name=kind,proto3,enum=typedb.protocol.ConceptDocument_Node_Leaf_Kind,oneof"`
}

func (*ConceptDocument_Node_Leaf_Empty_) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_EntityType) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_RelationType) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_AttributeType) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_RoleType) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_ValueType) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_Attribute) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_Value) isConceptDocument_Node_Leaf_Leaf() {}

func (*ConceptDocument_Node_Leaf_Kind_) isConceptDocument_Node_Leaf_Leaf() {}

type ConceptDocument_Node_Leaf_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptDocument_Node_Leaf_Empty) Reset() {
	*x = ConceptDocument_Node_Leaf_Empty{}
	mi := &file_answer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDocument_Node_Leaf_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDocument_Node_Leaf_Empty) ProtoMessage() {}

func (x *ConceptDocument_Node_Leaf_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_answer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDocument_Node_Leaf_Empty.ProtoReflect.Descriptor instead.
func (*ConceptDocument_Node_Leaf_Empty) Descriptor() ([]byte, []int) {
	return file_answer_proto_rawDescGZIP(), []int{2, 0, 2, 0}
}

var File_answer_proto protoreflect.FileDescriptor

const file_answer_proto_rawDesc = "" +
	"\n" +
	"\fanswer.proto\x12\x0ftypedb.protocol\x1a\rconcept.proto\"9\n" +
	"\n" +
	"ConceptRow\x12+\n" +
	"\x03row\x18\x01 \x03(\v2\x19.typedb.protocol.RowEntryR\x03row\"\xcf\x03\n" +
	"\bRowEntry\x127\n" +
	"\x05empty\x18\x01 \x01(\v2\x1f.typedb.protocol.RowEntry.EmptyH\x00R\x05empty\x124\n" +
	"\aconcept\x18\x02 \x01(\v2\x18.typedb.protocol.ConceptH\x00R\aconcept\x12.\n" +
	"\x05value\x18\x03 \x01(\v2\x16.typedb.protocol.ValueH\x00R\x05value\x12J\n" +
	"\fconcept_list\x18\x04 \x01(\v2%.typedb.protocol.RowEntry.ConceptListH\x00R\vconceptList\x12D\n" +
	"\n" +
	"value_list\x18\x05 \x01(\v2#.typedb.protocol.RowEntry.ValueListH\x00R\tvalueList\x1a\a\n" +
	"\x05Empty\x1aC\n" +
	"\vConceptList\x124\n" +
	"\bconcepts\x18\x01 \x03(\v2\x18.typedb.protocol.ConceptR\bconcepts\x1a;\n" +
	"\tValueList\x12.\n" +
	"\x06values\x18\x01 \x03(\v2\x16.typedb.protocol.ValueR\x06valuesB\a\n" +
	"\x05entry\"\xac\t\n" +
	"\x0fConceptDocument\x129\n" +
	"\x04root\x18\x01 \x01(\v2%.typedb.protocol.ConceptDocument.NodeR\x04root\x1a\xdd\b\n" +
	"\x04Node\x12=\n" +
	"\x03map\x18\x01 \x01(\v2).typedb.protocol.ConceptDocument.Node.MapH\x00R\x03map\x12@\n" +
	"\x04list\x18\x02 \x01(\v2*.typedb.protocol.ConceptDocument.Node.ListH\x00R\x04list\x12@\n" +
	"\x04leaf\x18\x03 \x01(\v2*.typedb.protocol.ConceptDocument.Node.LeafH\x00R\x04leaf\x1a\xaa\x01\n" +
	"\x03Map\x12D\n" +
	"\x03map\x18\x01 \x03(\v22.typedb.protocol.ConceptDocument.Node.Map.MapEntryR\x03map\x1a]\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.typedb.protocol.ConceptDocument.NodeR\x05value:\x028\x01\x1aA\n" +
	"\x04List\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.typedb.protocol.ConceptDocument.NodeR\x04list\x1a\x99\x05\n" +
	"\x04Leaf\x12H\n" +
	"\x05empty\x18\x01 \x01(\v20.typedb.protocol.ConceptDocument.Node.Leaf.EmptyH\x00R\x05empty\x12>\n" +
	"\ventity_type\x18\n" +
	" \x01(\v2\x1b.typedb.protocol.EntityTypeH\x00R\n" +
	"entityType\x12D\n" +
	"\rrelation_type\x18\v \x01(\v2\x1d.typedb.protocol.RelationTypeH\x00R\frelationType\x12G\n" +
	"\x0eattribute_type\x18\f \x01(\v2\x1e.typedb.protocol.AttributeTypeH\x00R\rattributeType\x128\n" +
	"\trole_type\x18\r \x01(\v2\x19.typedb.protocol.RoleTypeH\x00R\broleType\x12;\n" +
	"\n" +
	"value_type\x18\x0f \x01(\v2\x1a.typedb.protocol.ValueTypeH\x00R\tvalueType\x12:\n" +
	"\tattribute\x18\x14 \x01(\v2\x1a.typedb.protocol.AttributeH\x00R\tattribute\x12.\n" +
	"\x05value\x18\x15 \x01(\v2\x16.typedb.protocol.ValueH\x00R\x05value\x12E\n" +
	"\x04kind\x18\x1e \x01(\x0e2/.typedb.protocol.ConceptDocument.Node.Leaf.KindH\x00R\x04kind\x1a\a\n" +
	"\x05Empty\"=\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06Entity\x10\x00\x12\f\n" +
	"\bRelation\x10\x01\x12\x11\n" +
	"\rAttributeKind\x10\x03\x12\b\n" +
	"\x04Role\x10\x04B\x06\n" +
	"\x04leafB\x06\n" +
	"\x04nodeB1Z/github.com/joycheney/go-typedb-v3-grpc/pb/protob\x06proto3"

var (
	file_answer_proto_rawDescOnce sync.Once
	file_answer_proto_rawDescData []byte
)

func file_answer_proto_rawDescGZIP() []byte {
	file_answer_proto_rawDescOnce.Do(func() {
		file_answer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_answer_proto_rawDesc), len(file_answer_proto_rawDesc)))
	})
	return file_answer_proto_rawDescData
}

var file_answer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_answer_proto_goTypes = []any{
	(ConceptDocument_Node_Leaf_Kind)(0),     // 0: typedb.protocol.ConceptDocument.Node.Leaf.Kind
	(*ConceptRow)(nil),                      // 1: typedb.protocol.ConceptRow
	(*RowEntry)(nil),                        // 2: typedb.protocol.RowEntry
	(*ConceptDocument)(nil),                 // 3: typedb.protocol.ConceptDocument
	(*RowEntry_Empty)(nil),                  // 4: typedb.protocol.RowEntry.Empty
	(*RowEntry_ConceptList)(nil),            // 5: typedb.protocol.RowEntry.ConceptList
	(*RowEntry_ValueList)(nil),              // 6: typedb.protocol.RowEntry.ValueList
	(*ConceptDocument_Node)(nil),            // 7: typedb.protocol.ConceptDocument.Node
	(*ConceptDocument_Node_Map)(nil),        // 8: typedb.protocol.ConceptDocument.Node.Map
	(*ConceptDocument_Node_List)(nil),       // 9: typedb.protocol.ConceptDocument.Node.List
	(*ConceptDocument_Node_Leaf)(nil),       // 10: typedb.protocol.ConceptDocument.Node.Leaf
	nil,                                     // 11: typedb.protocol.ConceptDocument.Node.Map.MapEntry
	(*ConceptDocument_Node_Leaf_Empty)(nil), // 12: typedb.protocol.ConceptDocument.Node.Leaf.Empty
	(*Concept)(nil),                         // 13: typedb.protocol.Concept
	(*Value)(nil),                           // 14: typedb.protocol.Value
	(*EntityType)(nil),                      // 15: typedb.protocol.EntityType
	(*RelationType)(nil),                    // 16: typedb.protocol.RelationType
	(*AttributeType)(nil),                   // 17: typedb.protocol.AttributeType
	(*RoleType)(nil),                        // 18: typedb.protocol.RoleType
	(*ValueType)(nil),                       // 19: typedb.protocol.ValueType
	(*Attribute)(nil),                       // 20: typedb.protocol.Attribute
}
var file_answer_proto_depIdxs = []int32{
	2,  // 0: typedb.protocol.ConceptRow.row:type_name -> typedb.protocol.RowEntry
	4,  // 1: typedb.protocol.RowEntry.empty:type_name -> typedb.protocol.RowEntry.Empty
	13, // 2: typedb.protocol.RowEntry.concept:type_name -> typedb.protocol.Concept
	14, // 3: typedb.protocol.RowEntry.value:type_name -> typedb.protocol.Value
	5,  // 4: typedb.protocol.RowEntry.concept_list:type_name -> typedb.protocol.RowEntry.ConceptList
	6,  // 5: typedb.protocol.RowEntry.value_list:type_name -> typedb.protocol.RowEntry.ValueList
	7,  // 6: typedb.protocol.ConceptDocument.root:type_name -> typedb.protocol.ConceptDocument.Node
	13, // 7: typedb.protocol.RowEntry.ConceptList.concepts:type_name -> typedb.protocol.Concept
	14, // 8: typedb.protocol.RowEntry.ValueList.values:type_name -> typedb.protocol.Value
	8,  // 9: typedb.protocol.ConceptDocument.Node.map:type_name -> typedb.protocol.ConceptDocument.Node.Map
	9,  // 10: typedb.protocol.ConceptDocument.Node.list:type_name -> typedb.protocol.ConceptDocument.Node.List
	10, // 11: typedb.protocol.ConceptDocument.Node.leaf:type_name -> typedb.protocol.ConceptDocument.Node.Leaf
	11, // 12: typedb.protocol.ConceptDocument.Node.Map.map:type_name -> typedb.protocol.ConceptDocument.Node.Map.MapEntry
	7,  // 13: typedb.protocol.ConceptDocument.Node.List.list:type_name -> typedb.protocol.ConceptDocument.Node
	12, // 14: typedb.protocol.ConceptDocument.Node.Leaf.empty:type_name -> typedb.protocol.ConceptDocument.Node.Leaf.Empty
	15, // 15: typedb.protocol.ConceptDocument.Node.Leaf.entity_type:type_name -> typedb.protocol.EntityType
	16, // 16: typedb.protocol.ConceptDocument.Node.Leaf.relation_type:type_name -> typedb.protocol.RelationType
	17, // 17: typedb.protocol.ConceptDocument.Node.Leaf.attribute_type:type_name -> typedb.protocol.AttributeType
	18, // 18: typedb.protocol.ConceptDocument.Node.Leaf.role_type:type_name -> typedb.protocol.RoleType
	19, // 19: typedb.protocol.ConceptDocument.Node.Leaf.value_type:type_name -> typedb.protocol.ValueType
	20, // 20: typedb.protocol.ConceptDocument.Node.Leaf.attribute:type_name -> typedb.protocol.Attribute
	14, // 21: typedb.protocol.ConceptDocument.Node.Leaf.value:type_name -> typedb.protocol.Value
	0,  // 22: typedb.protocol.ConceptDocument.Node.Leaf.kind:type_name -> typedb.protocol.ConceptDocument.Node.Leaf.Kind
	7,  // 23: typedb.protocol.ConceptDocument.Node.Map.MapEntry.value:type_name -> typedb.protocol.ConceptDocument.Node
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_answer_proto_init() }
func file_answer_proto_init() {
	if File_answer_proto != nil {
		return
	}
	file_concept_proto_init()
	file_answer_proto_msgTypes[1].OneofWrappers = []any{
		(*RowEntry_Empty_)(nil),
		(*RowEntry_Concept)(nil),
		(*RowEntry_Value)(nil),
		(*RowEntry_ConceptList_)(nil),
		(*RowEntry_ValueList_)(nil),
	}
	file_answer_proto_msgTypes[6].OneofWrappers = []any{
		(*ConceptDocument_Node_Map_)(nil),
		(*ConceptDocument_Node_List_)(nil),
		(*ConceptDocument_Node_Leaf_)(nil),
	}
	file_answer_proto_msgTypes[9].OneofWrappers = []any{
		(*ConceptDocument_Node_Leaf_Empty_)(nil),
		(*ConceptDocument_Node_Leaf_EntityType)(nil),
		(*ConceptDocument_Node_Leaf_RelationType)(nil),
		(*ConceptDocument_Node_Leaf_AttributeType)(nil),
		(*ConceptDocument_Node_Leaf_RoleType)(nil),
		(*ConceptDocument_Node_Leaf_ValueType)(nil),
		(*ConceptDocument_Node_Leaf_Attribute)(nil),
		(*ConceptDocument_Node_Leaf_Value)(nil),
		(*ConceptDocument_Node_Leaf_Kind_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_answer_proto_rawDesc), len(file_answer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_answer_proto_goTypes,
		DependencyIndexes: file_answer_proto_depIdxs,
		EnumInfos:         file_answer_proto_enumTypes,
		MessageInfos:      file_answer_proto_msgTypes,
	}.Build()
	File_answer_proto = out.File
	file_answer_proto_goTypes = nil
	file_answer_proto_depIdxs = nil
}
