// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/authentication.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Authentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_proto_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_proto_authentication_proto_rawDescGZIP(), []int{0}
}

type Authentication_Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication_Token) Reset() {
	*x = Authentication_Token{}
	mi := &file_proto_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication_Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Token) ProtoMessage() {}

func (x *Authentication_Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Token.ProtoReflect.Descriptor instead.
func (*Authentication_Token) Descriptor() ([]byte, []int) {
	return file_proto_authentication_proto_rawDescGZIP(), []int{0, 0}
}

type Authentication_Token_Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication_Token_Create) Reset() {
	*x = Authentication_Token_Create{}
	mi := &file_proto_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication_Token_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Token_Create) ProtoMessage() {}

func (x *Authentication_Token_Create) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Token_Create.ProtoReflect.Descriptor instead.
func (*Authentication_Token_Create) Descriptor() ([]byte, []int) {
	return file_proto_authentication_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Authentication_Token_Create_Req struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credentials:
	//
	//	*Authentication_Token_Create_Req_Password_
	Credentials   isAuthentication_Token_Create_Req_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication_Token_Create_Req) Reset() {
	*x = Authentication_Token_Create_Req{}
	mi := &file_proto_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication_Token_Create_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Token_Create_Req) ProtoMessage() {}

func (x *Authentication_Token_Create_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Token_Create_Req.ProtoReflect.Descriptor instead.
func (*Authentication_Token_Create_Req) Descriptor() ([]byte, []int) {
	return file_proto_authentication_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Authentication_Token_Create_Req) GetCredentials() isAuthentication_Token_Create_Req_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Authentication_Token_Create_Req) GetPassword() *Authentication_Token_Create_Req_Password {
	if x != nil {
		if x, ok := x.Credentials.(*Authentication_Token_Create_Req_Password_); ok {
			return x.Password
		}
	}
	return nil
}

type isAuthentication_Token_Create_Req_Credentials interface {
	isAuthentication_Token_Create_Req_Credentials()
}

type Authentication_Token_Create_Req_Password_ struct {
	Password *Authentication_Token_Create_Req_Password `protobuf:"bytes,1,opt,name=password,proto3,oneof"` // extend by other credential kinds
}

func (*Authentication_Token_Create_Req_Password_) isAuthentication_Token_Create_Req_Credentials() {}

type Authentication_Token_Create_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication_Token_Create_Res) Reset() {
	*x = Authentication_Token_Create_Res{}
	mi := &file_proto_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication_Token_Create_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Token_Create_Res) ProtoMessage() {}

func (x *Authentication_Token_Create_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Token_Create_Res.ProtoReflect.Descriptor instead.
func (*Authentication_Token_Create_Res) Descriptor() ([]byte, []int) {
	return file_proto_authentication_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *Authentication_Token_Create_Res) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Authentication_Token_Create_Req_Password struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication_Token_Create_Req_Password) Reset() {
	*x = Authentication_Token_Create_Req_Password{}
	mi := &file_proto_authentication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication_Token_Create_Req_Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Token_Create_Req_Password) ProtoMessage() {}

func (x *Authentication_Token_Create_Req_Password) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Token_Create_Req_Password.ProtoReflect.Descriptor instead.
func (*Authentication_Token_Create_Req_Password) Descriptor() ([]byte, []int) {
	return file_proto_authentication_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *Authentication_Token_Create_Req_Password) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Authentication_Token_Create_Req_Password) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_authentication_proto protoreflect.FileDescriptor

const file_proto_authentication_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/authentication.proto\x12\x0ftypedb.protocol\"\xf6\x01\n" +
	"\x0eAuthentication\x1a\xe3\x01\n" +
	"\x05Token\x1a\xd9\x01\n" +
	"\x06Create\x1a\xb1\x01\n" +
	"\x03Req\x12W\n" +
	"\bpassword\x18\x01 \x01(\v29.typedb.protocol.Authentication.Token.Create.Req.PasswordH\x00R\bpassword\x1aB\n" +
	"\bPassword\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB\r\n" +
	"\vcredentials\x1a\x1b\n" +
	"\x03Res\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05tokenBCZAgithub.com/mcp-software-think-execute-server/go-typedb-v3-grpc/pbb\x06proto3"

var (
	file_proto_authentication_proto_rawDescOnce sync.Once
	file_proto_authentication_proto_rawDescData []byte
)

func file_proto_authentication_proto_rawDescGZIP() []byte {
	file_proto_authentication_proto_rawDescOnce.Do(func() {
		file_proto_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authentication_proto_rawDesc), len(file_proto_authentication_proto_rawDesc)))
	})
	return file_proto_authentication_proto_rawDescData
}

var file_proto_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_authentication_proto_goTypes = []any{
	(*Authentication)(nil),                           // 0: typedb.protocol.Authentication
	(*Authentication_Token)(nil),                     // 1: typedb.protocol.Authentication.Token
	(*Authentication_Token_Create)(nil),              // 2: typedb.protocol.Authentication.Token.Create
	(*Authentication_Token_Create_Req)(nil),          // 3: typedb.protocol.Authentication.Token.Create.Req
	(*Authentication_Token_Create_Res)(nil),          // 4: typedb.protocol.Authentication.Token.Create.Res
	(*Authentication_Token_Create_Req_Password)(nil), // 5: typedb.protocol.Authentication.Token.Create.Req.Password
}
var file_proto_authentication_proto_depIdxs = []int32{
	5, // 0: typedb.protocol.Authentication.Token.Create.Req.password:type_name -> typedb.protocol.Authentication.Token.Create.Req.Password
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_authentication_proto_init() }
func file_proto_authentication_proto_init() {
	if File_proto_authentication_proto != nil {
		return
	}
	file_proto_authentication_proto_msgTypes[3].OneofWrappers = []any{
		(*Authentication_Token_Create_Req_Password_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authentication_proto_rawDesc), len(file_proto_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_authentication_proto_goTypes,
		DependencyIndexes: file_proto_authentication_proto_depIdxs,
		MessageInfos:      file_proto_authentication_proto_msgTypes,
	}.Build()
	File_proto_authentication_proto = out.File
	file_proto_authentication_proto_goTypes = nil
	file_proto_authentication_proto_depIdxs = nil
}
