// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: concept.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Concept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Concept:
	//
	//	*Concept_EntityType
	//	*Concept_RelationType
	//	*Concept_AttributeType
	//	*Concept_RoleType
	//	*Concept_Entity
	//	*Concept_Relation
	//	*Concept_Attribute
	Concept       isConcept_Concept `protobuf_oneof:"concept"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Concept) Reset() {
	*x = Concept{}
	mi := &file_concept_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concept) ProtoMessage() {}

func (x *Concept) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concept.ProtoReflect.Descriptor instead.
func (*Concept) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{0}
}

func (x *Concept) GetConcept() isConcept_Concept {
	if x != nil {
		return x.Concept
	}
	return nil
}

func (x *Concept) GetEntityType() *EntityType {
	if x != nil {
		if x, ok := x.Concept.(*Concept_EntityType); ok {
			return x.EntityType
		}
	}
	return nil
}

func (x *Concept) GetRelationType() *RelationType {
	if x != nil {
		if x, ok := x.Concept.(*Concept_RelationType); ok {
			return x.RelationType
		}
	}
	return nil
}

func (x *Concept) GetAttributeType() *AttributeType {
	if x != nil {
		if x, ok := x.Concept.(*Concept_AttributeType); ok {
			return x.AttributeType
		}
	}
	return nil
}

func (x *Concept) GetRoleType() *RoleType {
	if x != nil {
		if x, ok := x.Concept.(*Concept_RoleType); ok {
			return x.RoleType
		}
	}
	return nil
}

func (x *Concept) GetEntity() *Entity {
	if x != nil {
		if x, ok := x.Concept.(*Concept_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *Concept) GetRelation() *Relation {
	if x != nil {
		if x, ok := x.Concept.(*Concept_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *Concept) GetAttribute() *Attribute {
	if x != nil {
		if x, ok := x.Concept.(*Concept_Attribute); ok {
			return x.Attribute
		}
	}
	return nil
}

type isConcept_Concept interface {
	isConcept_Concept()
}

type Concept_EntityType struct {
	EntityType *EntityType `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3,oneof"`
}

type Concept_RelationType struct {
	RelationType *RelationType `protobuf:"bytes,2,opt,name=relation_type,json=relationType,proto3,oneof"`
}

type Concept_AttributeType struct {
	AttributeType *AttributeType `protobuf:"bytes,3,opt,name=attribute_type,json=attributeType,proto3,oneof"`
}

type Concept_RoleType struct {
	RoleType *RoleType `protobuf:"bytes,4,opt,name=role_type,json=roleType,proto3,oneof"`
}

type Concept_Entity struct {
	Entity *Entity `protobuf:"bytes,5,opt,name=entity,proto3,oneof"`
}

type Concept_Relation struct {
	Relation *Relation `protobuf:"bytes,6,opt,name=relation,proto3,oneof"`
}

type Concept_Attribute struct {
	Attribute *Attribute `protobuf:"bytes,7,opt,name=attribute,proto3,oneof"`
}

func (*Concept_EntityType) isConcept_Concept() {}

func (*Concept_RelationType) isConcept_Concept() {}

func (*Concept_AttributeType) isConcept_Concept() {}

func (*Concept_RoleType) isConcept_Concept() {}

func (*Concept_Entity) isConcept_Concept() {}

func (*Concept_Relation) isConcept_Concept() {}

func (*Concept_Attribute) isConcept_Concept() {}

type Thing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Thing:
	//
	//	*Thing_Entity
	//	*Thing_Relation
	//	*Thing_Attribute
	Thing         isThing_Thing `protobuf_oneof:"thing"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thing) Reset() {
	*x = Thing{}
	mi := &file_concept_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing) ProtoMessage() {}

func (x *Thing) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thing.ProtoReflect.Descriptor instead.
func (*Thing) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{1}
}

func (x *Thing) GetThing() isThing_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

func (x *Thing) GetEntity() *Entity {
	if x != nil {
		if x, ok := x.Thing.(*Thing_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *Thing) GetRelation() *Relation {
	if x != nil {
		if x, ok := x.Thing.(*Thing_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *Thing) GetAttribute() *Attribute {
	if x != nil {
		if x, ok := x.Thing.(*Thing_Attribute); ok {
			return x.Attribute
		}
	}
	return nil
}

type isThing_Thing interface {
	isThing_Thing()
}

type Thing_Entity struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3,oneof"`
}

type Thing_Relation struct {
	Relation *Relation `protobuf:"bytes,2,opt,name=relation,proto3,oneof"`
}

type Thing_Attribute struct {
	Attribute *Attribute `protobuf:"bytes,3,opt,name=attribute,proto3,oneof"`
}

func (*Thing_Entity) isThing_Thing() {}

func (*Thing_Relation) isThing_Thing() {}

func (*Thing_Attribute) isThing_Thing() {}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iid           []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	EntityType    *EntityType            `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3,oneof" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_concept_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *Entity) GetEntityType() *EntityType {
	if x != nil {
		return x.EntityType
	}
	return nil
}

type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iid           []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	RelationType  *RelationType          `protobuf:"bytes,2,opt,name=relation_type,json=relationType,proto3,oneof" json:"relation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_concept_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{3}
}

func (x *Relation) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *Relation) GetRelationType() *RelationType {
	if x != nil {
		return x.RelationType
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iid           []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	AttributeType *AttributeType         `protobuf:"bytes,2,opt,name=attribute_type,json=attributeType,proto3,oneof" json:"attribute_type,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_concept_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{4}
}

func (x *Attribute) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *Attribute) GetAttributeType() *AttributeType {
	if x != nil {
		return x.AttributeType
	}
	return nil
}

func (x *Attribute) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_Boolean
	//	*Value_Integer
	//	*Value_Double
	//	*Value_Decimal_
	//	*Value_String_
	//	*Value_Date_
	//	*Value_Datetime_
	//	*Value_DatetimeTz
	//	*Value_Duration_
	//	*Value_Struct_
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_concept_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Value) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *Value) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *Value) GetDecimal() *Value_Decimal {
	if x != nil {
		if x, ok := x.Value.(*Value_Decimal_); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *Value) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*Value_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Value) GetDate() *Value_Date {
	if x != nil {
		if x, ok := x.Value.(*Value_Date_); ok {
			return x.Date
		}
	}
	return nil
}

func (x *Value) GetDatetime() *Value_Datetime {
	if x != nil {
		if x, ok := x.Value.(*Value_Datetime_); ok {
			return x.Datetime
		}
	}
	return nil
}

func (x *Value) GetDatetimeTz() *Value_Datetime_TZ {
	if x != nil {
		if x, ok := x.Value.(*Value_DatetimeTz); ok {
			return x.DatetimeTz
		}
	}
	return nil
}

func (x *Value) GetDuration() *Value_Duration {
	if x != nil {
		if x, ok := x.Value.(*Value_Duration_); ok {
			return x.Duration
		}
	}
	return nil
}

func (x *Value) GetStruct() *Value_Struct {
	if x != nil {
		if x, ok := x.Value.(*Value_Struct_); ok {
			return x.Struct
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,1,opt,name=boolean,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"zigzag64,2,opt,name=integer,proto3,oneof"`
}

type Value_Double struct {
	Double float64 `protobuf:"fixed64,3,opt,name=double,proto3,oneof"`
}

type Value_Decimal_ struct {
	Decimal *Value_Decimal `protobuf:"bytes,4,opt,name=decimal,proto3,oneof"`
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

type Value_Date_ struct {
	Date *Value_Date `protobuf:"bytes,6,opt,name=date,proto3,oneof"`
}

type Value_Datetime_ struct {
	Datetime *Value_Datetime `protobuf:"bytes,7,opt,name=datetime,proto3,oneof"`
}

type Value_DatetimeTz struct {
	DatetimeTz *Value_Datetime_TZ `protobuf:"bytes,8,opt,name=datetime_tz,json=datetimeTz,proto3,oneof"`
}

type Value_Duration_ struct {
	Duration *Value_Duration `protobuf:"bytes,9,opt,name=duration,proto3,oneof"`
}

type Value_Struct_ struct {
	Struct *Value_Struct `protobuf:"bytes,10,opt,name=struct,proto3,oneof"`
}

func (*Value_Boolean) isValue_Value() {}

func (*Value_Integer) isValue_Value() {}

func (*Value_Double) isValue_Value() {}

func (*Value_Decimal_) isValue_Value() {}

func (*Value_String_) isValue_Value() {}

func (*Value_Date_) isValue_Value() {}

func (*Value_Datetime_) isValue_Value() {}

func (*Value_DatetimeTz) isValue_Value() {}

func (*Value_Duration_) isValue_Value() {}

func (*Value_Struct_) isValue_Value() {}

type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Type_EntityType
	//	*Type_RelationType
	//	*Type_AttributeType
	//	*Type_RoleType
	Type          isType_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_concept_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{6}
}

func (x *Type) GetType() isType_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Type) GetEntityType() *EntityType {
	if x != nil {
		if x, ok := x.Type.(*Type_EntityType); ok {
			return x.EntityType
		}
	}
	return nil
}

func (x *Type) GetRelationType() *RelationType {
	if x != nil {
		if x, ok := x.Type.(*Type_RelationType); ok {
			return x.RelationType
		}
	}
	return nil
}

func (x *Type) GetAttributeType() *AttributeType {
	if x != nil {
		if x, ok := x.Type.(*Type_AttributeType); ok {
			return x.AttributeType
		}
	}
	return nil
}

func (x *Type) GetRoleType() *RoleType {
	if x != nil {
		if x, ok := x.Type.(*Type_RoleType); ok {
			return x.RoleType
		}
	}
	return nil
}

type isType_Type interface {
	isType_Type()
}

type Type_EntityType struct {
	EntityType *EntityType `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3,oneof"`
}

type Type_RelationType struct {
	RelationType *RelationType `protobuf:"bytes,2,opt,name=relation_type,json=relationType,proto3,oneof"`
}

type Type_AttributeType struct {
	AttributeType *AttributeType `protobuf:"bytes,3,opt,name=attribute_type,json=attributeType,proto3,oneof"`
}

type Type_RoleType struct {
	RoleType *RoleType `protobuf:"bytes,4,opt,name=role_type,json=roleType,proto3,oneof"`
}

func (*Type_EntityType) isType_Type() {}

func (*Type_RelationType) isType_Type() {}

func (*Type_AttributeType) isType_Type() {}

func (*Type_RoleType) isType_Type() {}

type RoleType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleType) Reset() {
	*x = RoleType{}
	mi := &file_concept_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleType) ProtoMessage() {}

func (x *RoleType) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleType.ProtoReflect.Descriptor instead.
func (*RoleType) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{7}
}

func (x *RoleType) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type EntityType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityType) Reset() {
	*x = EntityType{}
	mi := &file_concept_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityType) ProtoMessage() {}

func (x *EntityType) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityType.ProtoReflect.Descriptor instead.
func (*EntityType) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{8}
}

func (x *EntityType) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RelationType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationType) Reset() {
	*x = RelationType{}
	mi := &file_concept_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationType) ProtoMessage() {}

func (x *RelationType) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationType.ProtoReflect.Descriptor instead.
func (*RelationType) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{9}
}

func (x *RelationType) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type AttributeType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ValueType     *ValueType             `protobuf:"bytes,2,opt,name=value_type,json=valueType,proto3,oneof" json:"value_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeType) Reset() {
	*x = AttributeType{}
	mi := &file_concept_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeType) ProtoMessage() {}

func (x *AttributeType) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeType.ProtoReflect.Descriptor instead.
func (*AttributeType) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{10}
}

func (x *AttributeType) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AttributeType) GetValueType() *ValueType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

type ValueType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ValueType:
	//
	//	*ValueType_Boolean_
	//	*ValueType_Integer_
	//	*ValueType_Double_
	//	*ValueType_Decimal_
	//	*ValueType_String_
	//	*ValueType_Date_
	//	*ValueType_Datetime
	//	*ValueType_DatetimeTz
	//	*ValueType_Duration_
	//	*ValueType_Struct_
	ValueType     isValueType_ValueType `protobuf_oneof:"value_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType) Reset() {
	*x = ValueType{}
	mi := &file_concept_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType.ProtoReflect.Descriptor instead.
func (*ValueType) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11}
}

func (x *ValueType) GetValueType() isValueType_ValueType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

func (x *ValueType) GetBoolean() *ValueType_Boolean {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Boolean_); ok {
			return x.Boolean
		}
	}
	return nil
}

func (x *ValueType) GetInteger() *ValueType_Integer {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Integer_); ok {
			return x.Integer
		}
	}
	return nil
}

func (x *ValueType) GetDouble() *ValueType_Double {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Double_); ok {
			return x.Double
		}
	}
	return nil
}

func (x *ValueType) GetDecimal() *ValueType_Decimal {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Decimal_); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *ValueType) GetString_() *ValueType_String {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *ValueType) GetDate() *ValueType_Date {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Date_); ok {
			return x.Date
		}
	}
	return nil
}

func (x *ValueType) GetDatetime() *ValueType_DateTime {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Datetime); ok {
			return x.Datetime
		}
	}
	return nil
}

func (x *ValueType) GetDatetimeTz() *ValueType_DateTime_TZ {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_DatetimeTz); ok {
			return x.DatetimeTz
		}
	}
	return nil
}

func (x *ValueType) GetDuration() *ValueType_Duration {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Duration_); ok {
			return x.Duration
		}
	}
	return nil
}

func (x *ValueType) GetStruct() *ValueType_Struct {
	if x != nil {
		if x, ok := x.ValueType.(*ValueType_Struct_); ok {
			return x.Struct
		}
	}
	return nil
}

type isValueType_ValueType interface {
	isValueType_ValueType()
}

type ValueType_Boolean_ struct {
	Boolean *ValueType_Boolean `protobuf:"bytes,1,opt,name=boolean,proto3,oneof"`
}

type ValueType_Integer_ struct {
	Integer *ValueType_Integer `protobuf:"bytes,2,opt,name=integer,proto3,oneof"`
}

type ValueType_Double_ struct {
	Double *ValueType_Double `protobuf:"bytes,3,opt,name=double,proto3,oneof"`
}

type ValueType_Decimal_ struct {
	Decimal *ValueType_Decimal `protobuf:"bytes,4,opt,name=decimal,proto3,oneof"`
}

type ValueType_String_ struct {
	String_ *ValueType_String `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

type ValueType_Date_ struct {
	Date *ValueType_Date `protobuf:"bytes,6,opt,name=date,proto3,oneof"`
}

type ValueType_Datetime struct {
	Datetime *ValueType_DateTime `protobuf:"bytes,7,opt,name=datetime,proto3,oneof"`
}

type ValueType_DatetimeTz struct {
	DatetimeTz *ValueType_DateTime_TZ `protobuf:"bytes,8,opt,name=datetime_tz,json=datetimeTz,proto3,oneof"`
}

type ValueType_Duration_ struct {
	Duration *ValueType_Duration `protobuf:"bytes,9,opt,name=duration,proto3,oneof"`
}

type ValueType_Struct_ struct {
	Struct *ValueType_Struct `protobuf:"bytes,10,opt,name=struct,proto3,oneof"`
}

func (*ValueType_Boolean_) isValueType_ValueType() {}

func (*ValueType_Integer_) isValueType_ValueType() {}

func (*ValueType_Double_) isValueType_ValueType() {}

func (*ValueType_Decimal_) isValueType_ValueType() {}

func (*ValueType_String_) isValueType_ValueType() {}

func (*ValueType_Date_) isValueType_ValueType() {}

func (*ValueType_Datetime) isValueType_ValueType() {}

func (*ValueType_DatetimeTz) isValueType_ValueType() {}

func (*ValueType_Duration_) isValueType_ValueType() {}

func (*ValueType_Struct_) isValueType_ValueType() {}

type Value_Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integer       int64                  `protobuf:"zigzag64,1,opt,name=integer,proto3" json:"integer,omitempty"`
	Fractional    uint64                 `protobuf:"varint,2,opt,name=fractional,proto3" json:"fractional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_Decimal) Reset() {
	*x = Value_Decimal{}
	mi := &file_concept_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Decimal) ProtoMessage() {}

func (x *Value_Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Decimal.ProtoReflect.Descriptor instead.
func (*Value_Decimal) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Value_Decimal) GetInteger() int64 {
	if x != nil {
		return x.Integer
	}
	return 0
}

func (x *Value_Decimal) GetFractional() uint64 {
	if x != nil {
		return x.Fractional
	}
	return 0
}

type Value_Date struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// days since January 1, 0001 as day 1 in the Gregorian Calendar (following Rust conventions)
	NumDaysSinceCe int32 `protobuf:"zigzag32,1,opt,name=num_days_since_ce,json=numDaysSinceCe,proto3" json:"num_days_since_ce,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Value_Date) Reset() {
	*x = Value_Date{}
	mi := &file_concept_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Date) ProtoMessage() {}

func (x *Value_Date) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Date.ProtoReflect.Descriptor instead.
func (*Value_Date) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Value_Date) GetNumDaysSinceCe() int32 {
	if x != nil {
		return x.NumDaysSinceCe
	}
	return 0
}

type Value_Datetime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// seconds since epoch
	Seconds       int64  `protobuf:"zigzag64,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         uint32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_Datetime) Reset() {
	*x = Value_Datetime{}
	mi := &file_concept_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Datetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Datetime) ProtoMessage() {}

func (x *Value_Datetime) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Datetime.ProtoReflect.Descriptor instead.
func (*Value_Datetime) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Value_Datetime) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Value_Datetime) GetNanos() uint32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type Value_Datetime_TZ struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Datetime *Value_Datetime        `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	// Types that are valid to be assigned to Timezone:
	//
	//	*Value_Datetime_TZ_Named
	//	*Value_Datetime_TZ_Offset
	Timezone      isValue_Datetime_TZ_Timezone `protobuf_oneof:"timezone"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_Datetime_TZ) Reset() {
	*x = Value_Datetime_TZ{}
	mi := &file_concept_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Datetime_TZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Datetime_TZ) ProtoMessage() {}

func (x *Value_Datetime_TZ) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Datetime_TZ.ProtoReflect.Descriptor instead.
func (*Value_Datetime_TZ) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5, 3}
}

func (x *Value_Datetime_TZ) GetDatetime() *Value_Datetime {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *Value_Datetime_TZ) GetTimezone() isValue_Datetime_TZ_Timezone {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *Value_Datetime_TZ) GetNamed() string {
	if x != nil {
		if x, ok := x.Timezone.(*Value_Datetime_TZ_Named); ok {
			return x.Named
		}
	}
	return ""
}

func (x *Value_Datetime_TZ) GetOffset() int32 {
	if x != nil {
		if x, ok := x.Timezone.(*Value_Datetime_TZ_Offset); ok {
			return x.Offset
		}
	}
	return 0
}

type isValue_Datetime_TZ_Timezone interface {
	isValue_Datetime_TZ_Timezone()
}

type Value_Datetime_TZ_Named struct {
	Named string `protobuf:"bytes,2,opt,name=named,proto3,oneof"`
}

type Value_Datetime_TZ_Offset struct {
	// offset in seconds
	Offset int32 `protobuf:"zigzag32,3,opt,name=offset,proto3,oneof"`
}

func (*Value_Datetime_TZ_Named) isValue_Datetime_TZ_Timezone() {}

func (*Value_Datetime_TZ_Offset) isValue_Datetime_TZ_Timezone() {}

type Value_Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Months        uint32                 `protobuf:"varint,1,opt,name=months,proto3" json:"months,omitempty"`
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	Nanos         uint64                 `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_Duration) Reset() {
	*x = Value_Duration{}
	mi := &file_concept_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Duration) ProtoMessage() {}

func (x *Value_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Duration.ProtoReflect.Descriptor instead.
func (*Value_Duration) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5, 4}
}

func (x *Value_Duration) GetMonths() uint32 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *Value_Duration) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *Value_Duration) GetNanos() uint64 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type Value_Struct struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StructTypeName string                 `protobuf:"bytes,1,opt,name=struct_type_name,json=structTypeName,proto3" json:"struct_type_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Value_Struct) Reset() {
	*x = Value_Struct{}
	mi := &file_concept_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Struct) ProtoMessage() {}

func (x *Value_Struct) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Struct.ProtoReflect.Descriptor instead.
func (*Value_Struct) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{5, 5}
}

func (x *Value_Struct) GetStructTypeName() string {
	if x != nil {
		return x.StructTypeName
	}
	return ""
}

type ValueType_Boolean struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Boolean) Reset() {
	*x = ValueType_Boolean{}
	mi := &file_concept_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Boolean) ProtoMessage() {}

func (x *ValueType_Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Boolean.ProtoReflect.Descriptor instead.
func (*ValueType_Boolean) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 0}
}

type ValueType_Integer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Integer) Reset() {
	*x = ValueType_Integer{}
	mi := &file_concept_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Integer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Integer) ProtoMessage() {}

func (x *ValueType_Integer) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Integer.ProtoReflect.Descriptor instead.
func (*ValueType_Integer) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 1}
}

type ValueType_Double struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Double) Reset() {
	*x = ValueType_Double{}
	mi := &file_concept_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Double) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Double) ProtoMessage() {}

func (x *ValueType_Double) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Double.ProtoReflect.Descriptor instead.
func (*ValueType_Double) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 2}
}

type ValueType_Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Decimal) Reset() {
	*x = ValueType_Decimal{}
	mi := &file_concept_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Decimal) ProtoMessage() {}

func (x *ValueType_Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Decimal.ProtoReflect.Descriptor instead.
func (*ValueType_Decimal) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 3}
}

type ValueType_String struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_String) Reset() {
	*x = ValueType_String{}
	mi := &file_concept_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_String) ProtoMessage() {}

func (x *ValueType_String) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_String.ProtoReflect.Descriptor instead.
func (*ValueType_String) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 4}
}

type ValueType_Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Date) Reset() {
	*x = ValueType_Date{}
	mi := &file_concept_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Date) ProtoMessage() {}

func (x *ValueType_Date) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Date.ProtoReflect.Descriptor instead.
func (*ValueType_Date) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 5}
}

type ValueType_DateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_DateTime) Reset() {
	*x = ValueType_DateTime{}
	mi := &file_concept_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_DateTime) ProtoMessage() {}

func (x *ValueType_DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_DateTime.ProtoReflect.Descriptor instead.
func (*ValueType_DateTime) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 6}
}

type ValueType_DateTime_TZ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_DateTime_TZ) Reset() {
	*x = ValueType_DateTime_TZ{}
	mi := &file_concept_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_DateTime_TZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_DateTime_TZ) ProtoMessage() {}

func (x *ValueType_DateTime_TZ) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_DateTime_TZ.ProtoReflect.Descriptor instead.
func (*ValueType_DateTime_TZ) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 7}
}

type ValueType_Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Duration) Reset() {
	*x = ValueType_Duration{}
	mi := &file_concept_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Duration) ProtoMessage() {}

func (x *ValueType_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Duration.ProtoReflect.Descriptor instead.
func (*ValueType_Duration) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 8}
}

type ValueType_Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType_Struct) Reset() {
	*x = ValueType_Struct{}
	mi := &file_concept_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType_Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType_Struct) ProtoMessage() {}

func (x *ValueType_Struct) ProtoReflect() protoreflect.Message {
	mi := &file_concept_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType_Struct.ProtoReflect.Descriptor instead.
func (*ValueType_Struct) Descriptor() ([]byte, []int) {
	return file_concept_proto_rawDescGZIP(), []int{11, 9}
}

func (x *ValueType_Struct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_concept_proto protoreflect.FileDescriptor

const file_concept_proto_rawDesc = "" +
	"\n" +
	"\rconcept.proto\x12\x0ftypedb.protocol\"\xc5\x03\n" +
	"\aConcept\x12>\n" +
	"\ventity_type\x18\x01 \x01(\v2\x1b.typedb.protocol.EntityTypeH\x00R\n" +
	"entityType\x12D\n" +
	"\rrelation_type\x18\x02 \x01(\v2\x1d.typedb.protocol.RelationTypeH\x00R\frelationType\x12G\n" +
	"\x0eattribute_type\x18\x03 \x01(\v2\x1e.typedb.protocol.AttributeTypeH\x00R\rattributeType\x128\n" +
	"\trole_type\x18\x04 \x01(\v2\x19.typedb.protocol.RoleTypeH\x00R\broleType\x121\n" +
	"\x06entity\x18\x05 \x01(\v2\x17.typedb.protocol.EntityH\x00R\x06entity\x127\n" +
	"\brelation\x18\x06 \x01(\v2\x19.typedb.protocol.RelationH\x00R\brelation\x12:\n" +
	"\tattribute\x18\a \x01(\v2\x1a.typedb.protocol.AttributeH\x00R\tattributeB\t\n" +
	"\aconcept\"\xb8\x01\n" +
	"\x05Thing\x121\n" +
	"\x06entity\x18\x01 \x01(\v2\x17.typedb.protocol.EntityH\x00R\x06entity\x127\n" +
	"\brelation\x18\x02 \x01(\v2\x19.typedb.protocol.RelationH\x00R\brelation\x12:\n" +
	"\tattribute\x18\x03 \x01(\v2\x1a.typedb.protocol.AttributeH\x00R\tattributeB\a\n" +
	"\x05thing\"m\n" +
	"\x06Entity\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x12A\n" +
	"\ventity_type\x18\x02 \x01(\v2\x1b.typedb.protocol.EntityTypeH\x00R\n" +
	"entityType\x88\x01\x01B\x0e\n" +
	"\f_entity_type\"w\n" +
	"\bRelation\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x12G\n" +
	"\rrelation_type\x18\x02 \x01(\v2\x1d.typedb.protocol.RelationTypeH\x00R\frelationType\x88\x01\x01B\x10\n" +
	"\x0e_relation_type\"\xaa\x01\n" +
	"\tAttribute\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x12J\n" +
	"\x0eattribute_type\x18\x02 \x01(\v2\x1e.typedb.protocol.AttributeTypeH\x00R\rattributeType\x88\x01\x01\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.typedb.protocol.ValueR\x05valueB\x11\n" +
	"\x0f_attribute_type\"\xaa\a\n" +
	"\x05Value\x12\x1a\n" +
	"\aboolean\x18\x01 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x02 \x01(\x12H\x00R\ainteger\x12\x18\n" +
	"\x06double\x18\x03 \x01(\x01H\x00R\x06double\x12:\n" +
	"\adecimal\x18\x04 \x01(\v2\x1e.typedb.protocol.Value.DecimalH\x00R\adecimal\x12\x18\n" +
	"\x06string\x18\x05 \x01(\tH\x00R\x06string\x121\n" +
	"\x04date\x18\x06 \x01(\v2\x1b.typedb.protocol.Value.DateH\x00R\x04date\x12=\n" +
	"\bdatetime\x18\a \x01(\v2\x1f.typedb.protocol.Value.DatetimeH\x00R\bdatetime\x12E\n" +
	"\vdatetime_tz\x18\b \x01(\v2\".typedb.protocol.Value.Datetime_TZH\x00R\n" +
	"datetimeTz\x12=\n" +
	"\bduration\x18\t \x01(\v2\x1f.typedb.protocol.Value.DurationH\x00R\bduration\x127\n" +
	"\x06struct\x18\n" +
	" \x01(\v2\x1d.typedb.protocol.Value.StructH\x00R\x06struct\x1aC\n" +
	"\aDecimal\x12\x18\n" +
	"\ainteger\x18\x01 \x01(\x12R\ainteger\x12\x1e\n" +
	"\n" +
	"fractional\x18\x02 \x01(\x04R\n" +
	"fractional\x1a1\n" +
	"\x04Date\x12)\n" +
	"\x11num_days_since_ce\x18\x01 \x01(\x11R\x0enumDaysSinceCe\x1a:\n" +
	"\bDatetime\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x12R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\rR\x05nanos\x1a\x88\x01\n" +
	"\vDatetime_TZ\x12;\n" +
	"\bdatetime\x18\x01 \x01(\v2\x1f.typedb.protocol.Value.DatetimeR\bdatetime\x12\x16\n" +
	"\x05named\x18\x02 \x01(\tH\x00R\x05named\x12\x18\n" +
	"\x06offset\x18\x03 \x01(\x11H\x00R\x06offsetB\n" +
	"\n" +
	"\btimezone\x1aL\n" +
	"\bDuration\x12\x16\n" +
	"\x06months\x18\x01 \x01(\rR\x06months\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x04R\x05nanos\x1a2\n" +
	"\x06Struct\x12(\n" +
	"\x10struct_type_name\x18\x01 \x01(\tR\x0estructTypeNameB\a\n" +
	"\x05value\"\x97\x02\n" +
	"\x04Type\x12>\n" +
	"\ventity_type\x18\x01 \x01(\v2\x1b.typedb.protocol.EntityTypeH\x00R\n" +
	"entityType\x12D\n" +
	"\rrelation_type\x18\x02 \x01(\v2\x1d.typedb.protocol.RelationTypeH\x00R\frelationType\x12G\n" +
	"\x0eattribute_type\x18\x03 \x01(\v2\x1e.typedb.protocol.AttributeTypeH\x00R\rattributeType\x128\n" +
	"\trole_type\x18\x04 \x01(\v2\x19.typedb.protocol.RoleTypeH\x00R\broleTypeB\x06\n" +
	"\x04type\" \n" +
	"\bRoleType\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"\"\n" +
	"\n" +
	"EntityType\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"$\n" +
	"\fRelationType\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"t\n" +
	"\rAttributeType\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12>\n" +
	"\n" +
	"value_type\x18\x02 \x01(\v2\x1a.typedb.protocol.ValueTypeH\x00R\tvalueType\x88\x01\x01B\r\n" +
	"\v_value_type\"\x9a\x06\n" +
	"\tValueType\x12>\n" +
	"\aboolean\x18\x01 \x01(\v2\".typedb.protocol.ValueType.BooleanH\x00R\aboolean\x12>\n" +
	"\ainteger\x18\x02 \x01(\v2\".typedb.protocol.ValueType.IntegerH\x00R\ainteger\x12;\n" +
	"\x06double\x18\x03 \x01(\v2!.typedb.protocol.ValueType.DoubleH\x00R\x06double\x12>\n" +
	"\adecimal\x18\x04 \x01(\v2\".typedb.protocol.ValueType.DecimalH\x00R\adecimal\x12;\n" +
	"\x06string\x18\x05 \x01(\v2!.typedb.protocol.ValueType.StringH\x00R\x06string\x125\n" +
	"\x04date\x18\x06 \x01(\v2\x1f.typedb.protocol.ValueType.DateH\x00R\x04date\x12A\n" +
	"\bdatetime\x18\a \x01(\v2#.typedb.protocol.ValueType.DateTimeH\x00R\bdatetime\x12I\n" +
	"\vdatetime_tz\x18\b \x01(\v2&.typedb.protocol.ValueType.DateTime_TZH\x00R\n" +
	"datetimeTz\x12A\n" +
	"\bduration\x18\t \x01(\v2#.typedb.protocol.ValueType.DurationH\x00R\bduration\x12;\n" +
	"\x06struct\x18\n" +
	" \x01(\v2!.typedb.protocol.ValueType.StructH\x00R\x06struct\x1a\t\n" +
	"\aBoolean\x1a\t\n" +
	"\aInteger\x1a\b\n" +
	"\x06Double\x1a\t\n" +
	"\aDecimal\x1a\b\n" +
	"\x06String\x1a\x06\n" +
	"\x04Date\x1a\n" +
	"\n" +
	"\bDateTime\x1a\r\n" +
	"\vDateTime_TZ\x1a\n" +
	"\n" +
	"\bDuration\x1a\x1c\n" +
	"\x06Struct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\f\n" +
	"\n" +
	"value_typeB1Z/github.com/joycheney/go-typedb-v3-grpc/pb/protob\x06proto3"

var (
	file_concept_proto_rawDescOnce sync.Once
	file_concept_proto_rawDescData []byte
)

func file_concept_proto_rawDescGZIP() []byte {
	file_concept_proto_rawDescOnce.Do(func() {
		file_concept_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_concept_proto_rawDesc), len(file_concept_proto_rawDesc)))
	})
	return file_concept_proto_rawDescData
}

var file_concept_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_concept_proto_goTypes = []any{
	(*Concept)(nil),               // 0: typedb.protocol.Concept
	(*Thing)(nil),                 // 1: typedb.protocol.Thing
	(*Entity)(nil),                // 2: typedb.protocol.Entity
	(*Relation)(nil),              // 3: typedb.protocol.Relation
	(*Attribute)(nil),             // 4: typedb.protocol.Attribute
	(*Value)(nil),                 // 5: typedb.protocol.Value
	(*Type)(nil),                  // 6: typedb.protocol.Type
	(*RoleType)(nil),              // 7: typedb.protocol.RoleType
	(*EntityType)(nil),            // 8: typedb.protocol.EntityType
	(*RelationType)(nil),          // 9: typedb.protocol.RelationType
	(*AttributeType)(nil),         // 10: typedb.protocol.AttributeType
	(*ValueType)(nil),             // 11: typedb.protocol.ValueType
	(*Value_Decimal)(nil),         // 12: typedb.protocol.Value.Decimal
	(*Value_Date)(nil),            // 13: typedb.protocol.Value.Date
	(*Value_Datetime)(nil),        // 14: typedb.protocol.Value.Datetime
	(*Value_Datetime_TZ)(nil),     // 15: typedb.protocol.Value.Datetime_TZ
	(*Value_Duration)(nil),        // 16: typedb.protocol.Value.Duration
	(*Value_Struct)(nil),          // 17: typedb.protocol.Value.Struct
	(*ValueType_Boolean)(nil),     // 18: typedb.protocol.ValueType.Boolean
	(*ValueType_Integer)(nil),     // 19: typedb.protocol.ValueType.Integer
	(*ValueType_Double)(nil),      // 20: typedb.protocol.ValueType.Double
	(*ValueType_Decimal)(nil),     // 21: typedb.protocol.ValueType.Decimal
	(*ValueType_String)(nil),      // 22: typedb.protocol.ValueType.String
	(*ValueType_Date)(nil),        // 23: typedb.protocol.ValueType.Date
	(*ValueType_DateTime)(nil),    // 24: typedb.protocol.ValueType.DateTime
	(*ValueType_DateTime_TZ)(nil), // 25: typedb.protocol.ValueType.DateTime_TZ
	(*ValueType_Duration)(nil),    // 26: typedb.protocol.ValueType.Duration
	(*ValueType_Struct)(nil),      // 27: typedb.protocol.ValueType.Struct
}
var file_concept_proto_depIdxs = []int32{
	8,  // 0: typedb.protocol.Concept.entity_type:type_name -> typedb.protocol.EntityType
	9,  // 1: typedb.protocol.Concept.relation_type:type_name -> typedb.protocol.RelationType
	10, // 2: typedb.protocol.Concept.attribute_type:type_name -> typedb.protocol.AttributeType
	7,  // 3: typedb.protocol.Concept.role_type:type_name -> typedb.protocol.RoleType
	2,  // 4: typedb.protocol.Concept.entity:type_name -> typedb.protocol.Entity
	3,  // 5: typedb.protocol.Concept.relation:type_name -> typedb.protocol.Relation
	4,  // 6: typedb.protocol.Concept.attribute:type_name -> typedb.protocol.Attribute
	2,  // 7: typedb.protocol.Thing.entity:type_name -> typedb.protocol.Entity
	3,  // 8: typedb.protocol.Thing.relation:type_name -> typedb.protocol.Relation
	4,  // 9: typedb.protocol.Thing.attribute:type_name -> typedb.protocol.Attribute
	8,  // 10: typedb.protocol.Entity.entity_type:type_name -> typedb.protocol.EntityType
	9,  // 11: typedb.protocol.Relation.relation_type:type_name -> typedb.protocol.RelationType
	10, // 12: typedb.protocol.Attribute.attribute_type:type_name -> typedb.protocol.AttributeType
	5,  // 13: typedb.protocol.Attribute.value:type_name -> typedb.protocol.Value
	12, // 14: typedb.protocol.Value.decimal:type_name -> typedb.protocol.Value.Decimal
	13, // 15: typedb.protocol.Value.date:type_name -> typedb.protocol.Value.Date
	14, // 16: typedb.protocol.Value.datetime:type_name -> typedb.protocol.Value.Datetime
	15, // 17: typedb.protocol.Value.datetime_tz:type_name -> typedb.protocol.Value.Datetime_TZ
	16, // 18: typedb.protocol.Value.duration:type_name -> typedb.protocol.Value.Duration
	17, // 19: typedb.protocol.Value.struct:type_name -> typedb.protocol.Value.Struct
	8,  // 20: typedb.protocol.Type.entity_type:type_name -> typedb.protocol.EntityType
	9,  // 21: typedb.protocol.Type.relation_type:type_name -> typedb.protocol.RelationType
	10, // 22: typedb.protocol.Type.attribute_type:type_name -> typedb.protocol.AttributeType
	7,  // 23: typedb.protocol.Type.role_type:type_name -> typedb.protocol.RoleType
	11, // 24: typedb.protocol.AttributeType.value_type:type_name -> typedb.protocol.ValueType
	18, // 25: typedb.protocol.ValueType.boolean:type_name -> typedb.protocol.ValueType.Boolean
	19, // 26: typedb.protocol.ValueType.integer:type_name -> typedb.protocol.ValueType.Integer
	20, // 27: typedb.protocol.ValueType.double:type_name -> typedb.protocol.ValueType.Double
	21, // 28: typedb.protocol.ValueType.decimal:type_name -> typedb.protocol.ValueType.Decimal
	22, // 29: typedb.protocol.ValueType.string:type_name -> typedb.protocol.ValueType.String
	23, // 30: typedb.protocol.ValueType.date:type_name -> typedb.protocol.ValueType.Date
	24, // 31: typedb.protocol.ValueType.datetime:type_name -> typedb.protocol.ValueType.DateTime
	25, // 32: typedb.protocol.ValueType.datetime_tz:type_name -> typedb.protocol.ValueType.DateTime_TZ
	26, // 33: typedb.protocol.ValueType.duration:type_name -> typedb.protocol.ValueType.Duration
	27, // 34: typedb.protocol.ValueType.struct:type_name -> typedb.protocol.ValueType.Struct
	14, // 35: typedb.protocol.Value.Datetime_TZ.datetime:type_name -> typedb.protocol.Value.Datetime
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_concept_proto_init() }
func file_concept_proto_init() {
	if File_concept_proto != nil {
		return
	}
	file_concept_proto_msgTypes[0].OneofWrappers = []any{
		(*Concept_EntityType)(nil),
		(*Concept_RelationType)(nil),
		(*Concept_AttributeType)(nil),
		(*Concept_RoleType)(nil),
		(*Concept_Entity)(nil),
		(*Concept_Relation)(nil),
		(*Concept_Attribute)(nil),
	}
	file_concept_proto_msgTypes[1].OneofWrappers = []any{
		(*Thing_Entity)(nil),
		(*Thing_Relation)(nil),
		(*Thing_Attribute)(nil),
	}
	file_concept_proto_msgTypes[2].OneofWrappers = []any{}
	file_concept_proto_msgTypes[3].OneofWrappers = []any{}
	file_concept_proto_msgTypes[4].OneofWrappers = []any{}
	file_concept_proto_msgTypes[5].OneofWrappers = []any{
		(*Value_Boolean)(nil),
		(*Value_Integer)(nil),
		(*Value_Double)(nil),
		(*Value_Decimal_)(nil),
		(*Value_String_)(nil),
		(*Value_Date_)(nil),
		(*Value_Datetime_)(nil),
		(*Value_DatetimeTz)(nil),
		(*Value_Duration_)(nil),
		(*Value_Struct_)(nil),
	}
	file_concept_proto_msgTypes[6].OneofWrappers = []any{
		(*Type_EntityType)(nil),
		(*Type_RelationType)(nil),
		(*Type_AttributeType)(nil),
		(*Type_RoleType)(nil),
	}
	file_concept_proto_msgTypes[10].OneofWrappers = []any{}
	file_concept_proto_msgTypes[11].OneofWrappers = []any{
		(*ValueType_Boolean_)(nil),
		(*ValueType_Integer_)(nil),
		(*ValueType_Double_)(nil),
		(*ValueType_Decimal_)(nil),
		(*ValueType_String_)(nil),
		(*ValueType_Date_)(nil),
		(*ValueType_Datetime)(nil),
		(*ValueType_DatetimeTz)(nil),
		(*ValueType_Duration_)(nil),
		(*ValueType_Struct_)(nil),
	}
	file_concept_proto_msgTypes[15].OneofWrappers = []any{
		(*Value_Datetime_TZ_Named)(nil),
		(*Value_Datetime_TZ_Offset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_concept_proto_rawDesc), len(file_concept_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_concept_proto_goTypes,
		DependencyIndexes: file_concept_proto_depIdxs,
		MessageInfos:      file_concept_proto_msgTypes,
	}.Build()
	File_concept_proto = out.File
	file_concept_proto_goTypes = nil
	file_concept_proto_depIdxs = nil
}
