// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/connection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_proto_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{0}
}

// Connection ID and Token are expected in all message metadata
type ConnectionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionID) Reset() {
	*x = ConnectionID{}
	mi := &file_proto_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionID) ProtoMessage() {}

func (x *ConnectionID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionID.ProtoReflect.Descriptor instead.
func (*ConnectionID) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type Connection_Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection_Open) Reset() {
	*x = Connection_Open{}
	mi := &file_proto_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection_Open) ProtoMessage() {}

func (x *Connection_Open) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection_Open.ProtoReflect.Descriptor instead.
func (*Connection_Open) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{0, 0}
}

type Connection_Open_Req struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Version        Version                          `protobuf:"varint,1,opt,name=version,proto3,enum=typedb.protocol.Version" json:"version,omitempty"`
	DriverLang     string                           `protobuf:"bytes,2,opt,name=driver_lang,json=driverLang,proto3" json:"driver_lang,omitempty"`
	DriverVersion  string                           `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	Authentication *Authentication_Token_Create_Req `protobuf:"bytes,4,opt,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connection_Open_Req) Reset() {
	*x = Connection_Open_Req{}
	mi := &file_proto_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection_Open_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection_Open_Req) ProtoMessage() {}

func (x *Connection_Open_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection_Open_Req.ProtoReflect.Descriptor instead.
func (*Connection_Open_Req) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Connection_Open_Req) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_UNSPECIFIED
}

func (x *Connection_Open_Req) GetDriverLang() string {
	if x != nil {
		return x.DriverLang
	}
	return ""
}

func (x *Connection_Open_Req) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *Connection_Open_Req) GetAuthentication() *Authentication_Token_Create_Req {
	if x != nil {
		return x.Authentication
	}
	return nil
}

type Connection_Open_Res struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerDurationMillis uint64                 `protobuf:"varint,1,opt,name=server_duration_millis,json=serverDurationMillis,proto3" json:"server_duration_millis,omitempty"`
	ConnectionId         *ConnectionID          `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// pre-send all databases and replica info
	DatabasesAll   *DatabaseManager_All_Res         `protobuf:"bytes,3,opt,name=databases_all,json=databasesAll,proto3" json:"databases_all,omitempty"`
	Authentication *Authentication_Token_Create_Res `protobuf:"bytes,4,opt,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connection_Open_Res) Reset() {
	*x = Connection_Open_Res{}
	mi := &file_proto_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection_Open_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection_Open_Res) ProtoMessage() {}

func (x *Connection_Open_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection_Open_Res.ProtoReflect.Descriptor instead.
func (*Connection_Open_Res) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Connection_Open_Res) GetServerDurationMillis() uint64 {
	if x != nil {
		return x.ServerDurationMillis
	}
	return 0
}

func (x *Connection_Open_Res) GetConnectionId() *ConnectionID {
	if x != nil {
		return x.ConnectionId
	}
	return nil
}

func (x *Connection_Open_Res) GetDatabasesAll() *DatabaseManager_All_Res {
	if x != nil {
		return x.DatabasesAll
	}
	return nil
}

func (x *Connection_Open_Res) GetAuthentication() *Authentication_Token_Create_Res {
	if x != nil {
		return x.Authentication
	}
	return nil
}

var File_proto_connection_proto protoreflect.FileDescriptor

const file_proto_connection_proto_rawDesc = "" +
	"\n" +
	"\x16proto/connection.proto\x12\x0ftypedb.protocol\x1a\x1aproto/authentication.proto\x1a\x14proto/database.proto\x1a\x13proto/version.proto\"\x9e\x04\n" +
	"\n" +
	"Connection\x1a\x8f\x04\n" +
	"\x04Open\x1a\xdb\x01\n" +
	"\x03Req\x122\n" +
	"\aversion\x18\x01 \x01(\x0e2\x18.typedb.protocol.VersionR\aversion\x12\x1f\n" +
	"\vdriver_lang\x18\x02 \x01(\tR\n" +
	"driverLang\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\x12X\n" +
	"\x0eauthentication\x18\x04 \x01(\v20.typedb.protocol.Authentication.Token.Create.ReqR\x0eauthentication\x1a\xa8\x02\n" +
	"\x03Res\x124\n" +
	"\x16server_duration_millis\x18\x01 \x01(\x04R\x14serverDurationMillis\x12B\n" +
	"\rconnection_id\x18\x02 \x01(\v2\x1d.typedb.protocol.ConnectionIDR\fconnectionId\x12M\n" +
	"\rdatabases_all\x18\x03 \x01(\v2(.typedb.protocol.DatabaseManager.All.ResR\fdatabasesAll\x12X\n" +
	"\x0eauthentication\x18\x04 \x01(\v20.typedb.protocol.Authentication.Token.Create.ResR\x0eauthentication\"\x1e\n" +
	"\fConnectionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02idBCZAgithub.com/joycheney/go-typedb-v3-grpc/pbb\x06proto3"

var (
	file_proto_connection_proto_rawDescOnce sync.Once
	file_proto_connection_proto_rawDescData []byte
)

func file_proto_connection_proto_rawDescGZIP() []byte {
	file_proto_connection_proto_rawDescOnce.Do(func() {
		file_proto_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connection_proto_rawDesc), len(file_proto_connection_proto_rawDesc)))
	})
	return file_proto_connection_proto_rawDescData
}

var file_proto_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_connection_proto_goTypes = []any{
	(*Connection)(nil),                      // 0: typedb.protocol.Connection
	(*ConnectionID)(nil),                    // 1: typedb.protocol.ConnectionID
	(*Connection_Open)(nil),                 // 2: typedb.protocol.Connection.Open
	(*Connection_Open_Req)(nil),             // 3: typedb.protocol.Connection.Open.Req
	(*Connection_Open_Res)(nil),             // 4: typedb.protocol.Connection.Open.Res
	(Version)(0),                            // 5: typedb.protocol.Version
	(*Authentication_Token_Create_Req)(nil), // 6: typedb.protocol.Authentication.Token.Create.Req
	(*DatabaseManager_All_Res)(nil),         // 7: typedb.protocol.DatabaseManager.All.Res
	(*Authentication_Token_Create_Res)(nil), // 8: typedb.protocol.Authentication.Token.Create.Res
}
var file_proto_connection_proto_depIdxs = []int32{
	5, // 0: typedb.protocol.Connection.Open.Req.version:type_name -> typedb.protocol.Version
	6, // 1: typedb.protocol.Connection.Open.Req.authentication:type_name -> typedb.protocol.Authentication.Token.Create.Req
	1, // 2: typedb.protocol.Connection.Open.Res.connection_id:type_name -> typedb.protocol.ConnectionID
	7, // 3: typedb.protocol.Connection.Open.Res.databases_all:type_name -> typedb.protocol.DatabaseManager.All.Res
	8, // 4: typedb.protocol.Connection.Open.Res.authentication:type_name -> typedb.protocol.Authentication.Token.Create.Res
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_connection_proto_init() }
func file_proto_connection_proto_init() {
	if File_proto_connection_proto != nil {
		return
	}
	file_proto_authentication_proto_init()
	file_proto_database_proto_init()
	file_proto_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connection_proto_rawDesc), len(file_proto_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_connection_proto_goTypes,
		DependencyIndexes: file_proto_connection_proto_depIdxs,
		MessageInfos:      file_proto_connection_proto_msgTypes,
	}.Build()
	File_proto_connection_proto = out.File
	file_proto_connection_proto_goTypes = nil
	file_proto_connection_proto_depIdxs = nil
}
