// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/migration.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Migration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_proto_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0}
}

type Migration_Export struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Export) Reset() {
	*x = Migration_Export{}
	mi := &file_proto_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Export) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Export) ProtoMessage() {}

func (x *Migration_Export) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Export.ProtoReflect.Descriptor instead.
func (*Migration_Export) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 0}
}

type Migration_Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import) Reset() {
	*x = Migration_Import{}
	mi := &file_proto_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import) ProtoMessage() {}

func (x *Migration_Import) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import.ProtoReflect.Descriptor instead.
func (*Migration_Import) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1}
}

type Migration_Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*Migration_Item_Attribute_
	//	*Migration_Item_Entity_
	//	*Migration_Item_Relation_
	//	*Migration_Item_Header_
	//	*Migration_Item_Checksums_
	Item          isMigration_Item_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item) Reset() {
	*x = Migration_Item{}
	mi := &file_proto_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item) ProtoMessage() {}

func (x *Migration_Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item.ProtoReflect.Descriptor instead.
func (*Migration_Item) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Migration_Item) GetItem() isMigration_Item_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Migration_Item) GetAttribute() *Migration_Item_Attribute {
	if x != nil {
		if x, ok := x.Item.(*Migration_Item_Attribute_); ok {
			return x.Attribute
		}
	}
	return nil
}

func (x *Migration_Item) GetEntity() *Migration_Item_Entity {
	if x != nil {
		if x, ok := x.Item.(*Migration_Item_Entity_); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *Migration_Item) GetRelation() *Migration_Item_Relation {
	if x != nil {
		if x, ok := x.Item.(*Migration_Item_Relation_); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *Migration_Item) GetHeader() *Migration_Item_Header {
	if x != nil {
		if x, ok := x.Item.(*Migration_Item_Header_); ok {
			return x.Header
		}
	}
	return nil
}

func (x *Migration_Item) GetChecksums() *Migration_Item_Checksums {
	if x != nil {
		if x, ok := x.Item.(*Migration_Item_Checksums_); ok {
			return x.Checksums
		}
	}
	return nil
}

type isMigration_Item_Item interface {
	isMigration_Item_Item()
}

type Migration_Item_Attribute_ struct {
	Attribute *Migration_Item_Attribute `protobuf:"bytes,1,opt,name=attribute,proto3,oneof"`
}

type Migration_Item_Entity_ struct {
	Entity *Migration_Item_Entity `protobuf:"bytes,2,opt,name=entity,proto3,oneof"`
}

type Migration_Item_Relation_ struct {
	Relation *Migration_Item_Relation `protobuf:"bytes,3,opt,name=relation,proto3,oneof"`
}

type Migration_Item_Header_ struct {
	Header *Migration_Item_Header `protobuf:"bytes,15,opt,name=header,proto3,oneof"`
}

type Migration_Item_Checksums_ struct {
	Checksums *Migration_Item_Checksums `protobuf:"bytes,16,opt,name=checksums,proto3,oneof"`
}

func (*Migration_Item_Attribute_) isMigration_Item_Item() {}

func (*Migration_Item_Entity_) isMigration_Item_Item() {}

func (*Migration_Item_Relation_) isMigration_Item_Item() {}

func (*Migration_Item_Header_) isMigration_Item_Item() {}

func (*Migration_Item_Checksums_) isMigration_Item_Item() {}

type Migration_MigrationValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Migration_MigrationValue_String_
	//	*Migration_MigrationValue_Boolean
	//	*Migration_MigrationValue_Integer
	//	*Migration_MigrationValue_Double
	//	*Migration_MigrationValue_DatetimeMillis
	//	*Migration_MigrationValue_Decimal
	//	*Migration_MigrationValue_Date
	//	*Migration_MigrationValue_Datetime
	//	*Migration_MigrationValue_DatetimeTz
	//	*Migration_MigrationValue_Duration
	//	*Migration_MigrationValue_Struct
	Value         isMigration_MigrationValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_MigrationValue) Reset() {
	*x = Migration_MigrationValue{}
	mi := &file_proto_migration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_MigrationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_MigrationValue) ProtoMessage() {}

func (x *Migration_MigrationValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_MigrationValue.ProtoReflect.Descriptor instead.
func (*Migration_MigrationValue) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Migration_MigrationValue) GetValue() isMigration_MigrationValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Migration_MigrationValue) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Migration_MigrationValue) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Migration_MigrationValue) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *Migration_MigrationValue) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *Migration_MigrationValue) GetDatetimeMillis() int64 {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_DatetimeMillis); ok {
			return x.DatetimeMillis
		}
	}
	return 0
}

func (x *Migration_MigrationValue) GetDecimal() *Value_Decimal {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *Migration_MigrationValue) GetDate() *Value_Date {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *Migration_MigrationValue) GetDatetime() *Value_Datetime {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Datetime); ok {
			return x.Datetime
		}
	}
	return nil
}

func (x *Migration_MigrationValue) GetDatetimeTz() *Value_Datetime_TZ {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_DatetimeTz); ok {
			return x.DatetimeTz
		}
	}
	return nil
}

func (x *Migration_MigrationValue) GetDuration() *Value_Duration {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Duration); ok {
			return x.Duration
		}
	}
	return nil
}

func (x *Migration_MigrationValue) GetStruct() *Value_Struct {
	if x != nil {
		if x, ok := x.Value.(*Migration_MigrationValue_Struct); ok {
			return x.Struct
		}
	}
	return nil
}

type isMigration_MigrationValue_Value interface {
	isMigration_MigrationValue_Value()
}

type Migration_MigrationValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Migration_MigrationValue_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}

type Migration_MigrationValue_Integer struct {
	Integer int64 `protobuf:"varint,3,opt,name=integer,proto3,oneof"`
}

type Migration_MigrationValue_Double struct {
	Double float64 `protobuf:"fixed64,4,opt,name=double,proto3,oneof"`
}

type Migration_MigrationValue_DatetimeMillis struct {
	DatetimeMillis int64 `protobuf:"varint,5,opt,name=datetime_millis,json=datetimeMillis,proto3,oneof"` // compatibility with 2.x, milliseconds since epoch
}

type Migration_MigrationValue_Decimal struct {
	Decimal *Value_Decimal `protobuf:"bytes,6,opt,name=decimal,proto3,oneof"`
}

type Migration_MigrationValue_Date struct {
	Date *Value_Date `protobuf:"bytes,8,opt,name=date,proto3,oneof"`
}

type Migration_MigrationValue_Datetime struct {
	Datetime *Value_Datetime `protobuf:"bytes,9,opt,name=datetime,proto3,oneof"`
}

type Migration_MigrationValue_DatetimeTz struct {
	DatetimeTz *Value_Datetime_TZ `protobuf:"bytes,10,opt,name=datetime_tz,json=datetimeTz,proto3,oneof"`
}

type Migration_MigrationValue_Duration struct {
	Duration *Value_Duration `protobuf:"bytes,11,opt,name=duration,proto3,oneof"`
}

type Migration_MigrationValue_Struct struct {
	Struct *Value_Struct `protobuf:"bytes,12,opt,name=struct,proto3,oneof"`
}

func (*Migration_MigrationValue_String_) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Boolean) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Integer) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Double) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_DatetimeMillis) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Decimal) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Date) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Datetime) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_DatetimeTz) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Duration) isMigration_MigrationValue_Value() {}

func (*Migration_MigrationValue_Struct) isMigration_MigrationValue_Value() {}

type Migration_Export_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Export_Req) Reset() {
	*x = Migration_Export_Req{}
	mi := &file_proto_migration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Export_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Export_Req) ProtoMessage() {}

func (x *Migration_Export_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Export_Req.ProtoReflect.Descriptor instead.
func (*Migration_Export_Req) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Migration_Export_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Migration_Export_Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Server:
	//
	//	*Migration_Export_Server_InitialRes
	//	*Migration_Export_Server_ResPart
	//	*Migration_Export_Server_Done
	Server        isMigration_Export_Server_Server `protobuf_oneof:"server"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Export_Server) Reset() {
	*x = Migration_Export_Server{}
	mi := &file_proto_migration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Export_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Export_Server) ProtoMessage() {}

func (x *Migration_Export_Server) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Export_Server.ProtoReflect.Descriptor instead.
func (*Migration_Export_Server) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Migration_Export_Server) GetServer() isMigration_Export_Server_Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Migration_Export_Server) GetInitialRes() *Migration_Export_InitialRes {
	if x != nil {
		if x, ok := x.Server.(*Migration_Export_Server_InitialRes); ok {
			return x.InitialRes
		}
	}
	return nil
}

func (x *Migration_Export_Server) GetResPart() *Migration_Export_ResPart {
	if x != nil {
		if x, ok := x.Server.(*Migration_Export_Server_ResPart); ok {
			return x.ResPart
		}
	}
	return nil
}

func (x *Migration_Export_Server) GetDone() *Migration_Export_Done {
	if x != nil {
		if x, ok := x.Server.(*Migration_Export_Server_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isMigration_Export_Server_Server interface {
	isMigration_Export_Server_Server()
}

type Migration_Export_Server_InitialRes struct {
	InitialRes *Migration_Export_InitialRes `protobuf:"bytes,1,opt,name=initial_res,json=initialRes,proto3,oneof"`
}

type Migration_Export_Server_ResPart struct {
	ResPart *Migration_Export_ResPart `protobuf:"bytes,2,opt,name=res_part,json=resPart,proto3,oneof"`
}

type Migration_Export_Server_Done struct {
	Done *Migration_Export_Done `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

func (*Migration_Export_Server_InitialRes) isMigration_Export_Server_Server() {}

func (*Migration_Export_Server_ResPart) isMigration_Export_Server_Server() {}

func (*Migration_Export_Server_Done) isMigration_Export_Server_Server() {}

type Migration_Export_InitialRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Export_InitialRes) Reset() {
	*x = Migration_Export_InitialRes{}
	mi := &file_proto_migration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Export_InitialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Export_InitialRes) ProtoMessage() {}

func (x *Migration_Export_InitialRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Export_InitialRes.ProtoReflect.Descriptor instead.
func (*Migration_Export_InitialRes) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Migration_Export_InitialRes) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type Migration_Export_ResPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Migration_Item      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Export_ResPart) Reset() {
	*x = Migration_Export_ResPart{}
	mi := &file_proto_migration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Export_ResPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Export_ResPart) ProtoMessage() {}

func (x *Migration_Export_ResPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Export_ResPart.ProtoReflect.Descriptor instead.
func (*Migration_Export_ResPart) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Migration_Export_ResPart) GetItems() []*Migration_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Migration_Export_Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Export_Done) Reset() {
	*x = Migration_Export_Done{}
	mi := &file_proto_migration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Export_Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Export_Done) ProtoMessage() {}

func (x *Migration_Export_Done) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Export_Done.ProtoReflect.Descriptor instead.
func (*Migration_Export_Done) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 0, 4}
}

type Migration_Import_Client struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Client:
	//
	//	*Migration_Import_Client_InitialReq_
	//	*Migration_Import_Client_ReqPart_
	//	*Migration_Import_Client_Done_
	Client        isMigration_Import_Client_Client `protobuf_oneof:"client"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import_Client) Reset() {
	*x = Migration_Import_Client{}
	mi := &file_proto_migration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import_Client) ProtoMessage() {}

func (x *Migration_Import_Client) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import_Client.ProtoReflect.Descriptor instead.
func (*Migration_Import_Client) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Migration_Import_Client) GetClient() isMigration_Import_Client_Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Migration_Import_Client) GetInitialReq() *Migration_Import_Client_InitialReq {
	if x != nil {
		if x, ok := x.Client.(*Migration_Import_Client_InitialReq_); ok {
			return x.InitialReq
		}
	}
	return nil
}

func (x *Migration_Import_Client) GetReqPart() *Migration_Import_Client_ReqPart {
	if x != nil {
		if x, ok := x.Client.(*Migration_Import_Client_ReqPart_); ok {
			return x.ReqPart
		}
	}
	return nil
}

func (x *Migration_Import_Client) GetDone() *Migration_Import_Client_Done {
	if x != nil {
		if x, ok := x.Client.(*Migration_Import_Client_Done_); ok {
			return x.Done
		}
	}
	return nil
}

type isMigration_Import_Client_Client interface {
	isMigration_Import_Client_Client()
}

type Migration_Import_Client_InitialReq_ struct {
	InitialReq *Migration_Import_Client_InitialReq `protobuf:"bytes,1,opt,name=initial_req,json=initialReq,proto3,oneof"`
}

type Migration_Import_Client_ReqPart_ struct {
	ReqPart *Migration_Import_Client_ReqPart `protobuf:"bytes,2,opt,name=req_part,json=reqPart,proto3,oneof"`
}

type Migration_Import_Client_Done_ struct {
	Done *Migration_Import_Client_Done `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

func (*Migration_Import_Client_InitialReq_) isMigration_Import_Client_Client() {}

func (*Migration_Import_Client_ReqPart_) isMigration_Import_Client_Client() {}

func (*Migration_Import_Client_Done_) isMigration_Import_Client_Client() {}

type Migration_Import_Server struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Done          *Migration_Import_Server_Done `protobuf:"bytes,1,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import_Server) Reset() {
	*x = Migration_Import_Server{}
	mi := &file_proto_migration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import_Server) ProtoMessage() {}

func (x *Migration_Import_Server) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import_Server.ProtoReflect.Descriptor instead.
func (*Migration_Import_Server) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Migration_Import_Server) GetDone() *Migration_Import_Server_Done {
	if x != nil {
		return x.Done
	}
	return nil
}

type Migration_Import_Client_InitialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import_Client_InitialReq) Reset() {
	*x = Migration_Import_Client_InitialReq{}
	mi := &file_proto_migration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import_Client_InitialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import_Client_InitialReq) ProtoMessage() {}

func (x *Migration_Import_Client_InitialReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import_Client_InitialReq.ProtoReflect.Descriptor instead.
func (*Migration_Import_Client_InitialReq) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *Migration_Import_Client_InitialReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Migration_Import_Client_InitialReq) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type Migration_Import_Client_ReqPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Migration_Item      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import_Client_ReqPart) Reset() {
	*x = Migration_Import_Client_ReqPart{}
	mi := &file_proto_migration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import_Client_ReqPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import_Client_ReqPart) ProtoMessage() {}

func (x *Migration_Import_Client_ReqPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import_Client_ReqPart.ProtoReflect.Descriptor instead.
func (*Migration_Import_Client_ReqPart) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1, 0, 1}
}

func (x *Migration_Import_Client_ReqPart) GetItems() []*Migration_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Migration_Import_Client_Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import_Client_Done) Reset() {
	*x = Migration_Import_Client_Done{}
	mi := &file_proto_migration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import_Client_Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import_Client_Done) ProtoMessage() {}

func (x *Migration_Import_Client_Done) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import_Client_Done.ProtoReflect.Descriptor instead.
func (*Migration_Import_Client_Done) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1, 0, 2}
}

type Migration_Import_Server_Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Import_Server_Done) Reset() {
	*x = Migration_Import_Server_Done{}
	mi := &file_proto_migration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Import_Server_Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Import_Server_Done) ProtoMessage() {}

func (x *Migration_Import_Server_Done) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Import_Server_Done.ProtoReflect.Descriptor instead.
func (*Migration_Import_Server_Done) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

type Migration_Item_Entity struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Id            string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                           `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Attributes    []*Migration_Item_OwnedAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item_Entity) Reset() {
	*x = Migration_Item_Entity{}
	mi := &file_proto_migration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Entity) ProtoMessage() {}

func (x *Migration_Item_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Entity.ProtoReflect.Descriptor instead.
func (*Migration_Item_Entity) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Migration_Item_Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration_Item_Entity) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Migration_Item_Entity) GetAttributes() []*Migration_Item_OwnedAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Migration_Item_Attribute struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Id            string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                           `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Attributes    []*Migration_Item_OwnedAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"` // empty in 3.x, used for backwards compatibility
	Value         *Migration_MigrationValue        `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item_Attribute) Reset() {
	*x = Migration_Item_Attribute{}
	mi := &file_proto_migration_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Attribute) ProtoMessage() {}

func (x *Migration_Item_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Attribute.ProtoReflect.Descriptor instead.
func (*Migration_Item_Attribute) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Migration_Item_Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration_Item_Attribute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Migration_Item_Attribute) GetAttributes() []*Migration_Item_OwnedAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Migration_Item_Attribute) GetValue() *Migration_MigrationValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type Migration_Item_Relation struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Id            string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                           `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Attributes    []*Migration_Item_OwnedAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Roles         []*Migration_Item_Relation_Role  `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item_Relation) Reset() {
	*x = Migration_Item_Relation{}
	mi := &file_proto_migration_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Relation) ProtoMessage() {}

func (x *Migration_Item_Relation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Relation.ProtoReflect.Descriptor instead.
func (*Migration_Item_Relation) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 2}
}

func (x *Migration_Item_Relation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration_Item_Relation) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Migration_Item_Relation) GetAttributes() []*Migration_Item_OwnedAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Migration_Item_Relation) GetRoles() []*Migration_Item_Relation_Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Migration_Item_OwnedAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item_OwnedAttribute) Reset() {
	*x = Migration_Item_OwnedAttribute{}
	mi := &file_proto_migration_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_OwnedAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_OwnedAttribute) ProtoMessage() {}

func (x *Migration_Item_OwnedAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_OwnedAttribute.ProtoReflect.Descriptor instead.
func (*Migration_Item_OwnedAttribute) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 3}
}

func (x *Migration_Item_OwnedAttribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Migration_Item_Header struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TypedbVersion    string                 `protobuf:"bytes,1,opt,name=typedb_version,json=typedbVersion,proto3" json:"typedb_version,omitempty"`
	OriginalDatabase string                 `protobuf:"bytes,2,opt,name=original_database,json=originalDatabase,proto3" json:"original_database,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Migration_Item_Header) Reset() {
	*x = Migration_Item_Header{}
	mi := &file_proto_migration_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Header) ProtoMessage() {}

func (x *Migration_Item_Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Header.ProtoReflect.Descriptor instead.
func (*Migration_Item_Header) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 4}
}

func (x *Migration_Item_Header) GetTypedbVersion() string {
	if x != nil {
		return x.TypedbVersion
	}
	return ""
}

func (x *Migration_Item_Header) GetOriginalDatabase() string {
	if x != nil {
		return x.OriginalDatabase
	}
	return ""
}

type Migration_Item_Checksums struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityCount    int64                  `protobuf:"varint,1,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`
	AttributeCount int64                  `protobuf:"varint,2,opt,name=attribute_count,json=attributeCount,proto3" json:"attribute_count,omitempty"`
	RelationCount  int64                  `protobuf:"varint,3,opt,name=relation_count,json=relationCount,proto3" json:"relation_count,omitempty"`
	RoleCount      int64                  `protobuf:"varint,4,opt,name=role_count,json=roleCount,proto3" json:"role_count,omitempty"`
	OwnershipCount int64                  `protobuf:"varint,5,opt,name=ownership_count,json=ownershipCount,proto3" json:"ownership_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Migration_Item_Checksums) Reset() {
	*x = Migration_Item_Checksums{}
	mi := &file_proto_migration_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Checksums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Checksums) ProtoMessage() {}

func (x *Migration_Item_Checksums) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Checksums.ProtoReflect.Descriptor instead.
func (*Migration_Item_Checksums) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 5}
}

func (x *Migration_Item_Checksums) GetEntityCount() int64 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

func (x *Migration_Item_Checksums) GetAttributeCount() int64 {
	if x != nil {
		return x.AttributeCount
	}
	return 0
}

func (x *Migration_Item_Checksums) GetRelationCount() int64 {
	if x != nil {
		return x.RelationCount
	}
	return 0
}

func (x *Migration_Item_Checksums) GetRoleCount() int64 {
	if x != nil {
		return x.RoleCount
	}
	return 0
}

func (x *Migration_Item_Checksums) GetOwnershipCount() int64 {
	if x != nil {
		return x.OwnershipCount
	}
	return 0
}

type Migration_Item_Relation_Role struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Label         string                                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Players       []*Migration_Item_Relation_Role_Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item_Relation_Role) Reset() {
	*x = Migration_Item_Relation_Role{}
	mi := &file_proto_migration_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Relation_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Relation_Role) ProtoMessage() {}

func (x *Migration_Item_Relation_Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Relation_Role.ProtoReflect.Descriptor instead.
func (*Migration_Item_Relation_Role) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 2, 0}
}

func (x *Migration_Item_Relation_Role) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Migration_Item_Relation_Role) GetPlayers() []*Migration_Item_Relation_Role_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Migration_Item_Relation_Role_Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration_Item_Relation_Role_Player) Reset() {
	*x = Migration_Item_Relation_Role_Player{}
	mi := &file_proto_migration_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration_Item_Relation_Role_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_Item_Relation_Role_Player) ProtoMessage() {}

func (x *Migration_Item_Relation_Role_Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_migration_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_Item_Relation_Role_Player.ProtoReflect.Descriptor instead.
func (*Migration_Item_Relation_Role_Player) Descriptor() ([]byte, []int) {
	return file_proto_migration_proto_rawDescGZIP(), []int{0, 2, 2, 0, 0}
}

func (x *Migration_Item_Relation_Role_Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_migration_proto protoreflect.FileDescriptor

const file_proto_migration_proto_rawDesc = "" +
	"\n" +
	"\x15proto/migration.proto\x12\x0ftypedb.protocol\x1a\x13proto/concept.proto\"\xea\x15\n" +
	"\tMigration\x1a\xff\x02\n" +
	"\x06Export\x1a\x19\n" +
	"\x03Req\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\xe9\x01\n" +
	"\x06Server\x12O\n" +
	"\vinitial_res\x18\x01 \x01(\v2,.typedb.protocol.Migration.Export.InitialResH\x00R\n" +
	"initialRes\x12F\n" +
	"\bres_part\x18\x02 \x01(\v2).typedb.protocol.Migration.Export.ResPartH\x00R\aresPart\x12<\n" +
	"\x04done\x18\x03 \x01(\v2&.typedb.protocol.Migration.Export.DoneH\x00R\x04doneB\b\n" +
	"\x06server\x1a$\n" +
	"\n" +
	"InitialRes\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x1a@\n" +
	"\aResPart\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.typedb.protocol.Migration.ItemR\x05items\x1a\x06\n" +
	"\x04Done\x1a\xe2\x03\n" +
	"\x06Import\x1a\x82\x03\n" +
	"\x06Client\x12V\n" +
	"\vinitial_req\x18\x01 \x01(\v23.typedb.protocol.Migration.Import.Client.InitialReqH\x00R\n" +
	"initialReq\x12M\n" +
	"\breq_part\x18\x02 \x01(\v20.typedb.protocol.Migration.Import.Client.ReqPartH\x00R\areqPart\x12C\n" +
	"\x04done\x18\x03 \x01(\v2-.typedb.protocol.Migration.Import.Client.DoneH\x00R\x04done\x1a8\n" +
	"\n" +
	"InitialReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x1a@\n" +
	"\aReqPart\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.typedb.protocol.Migration.ItemR\x05items\x1a\x06\n" +
	"\x04DoneB\b\n" +
	"\x06client\x1aS\n" +
	"\x06Server\x12A\n" +
	"\x04done\x18\x01 \x01(\v2-.typedb.protocol.Migration.Import.Server.DoneR\x04done\x1a\x06\n" +
	"\x04Done\x1a\xd5\n" +
	"\n" +
	"\x04Item\x12I\n" +
	"\tattribute\x18\x01 \x01(\v2).typedb.protocol.Migration.Item.AttributeH\x00R\tattribute\x12@\n" +
	"\x06entity\x18\x02 \x01(\v2&.typedb.protocol.Migration.Item.EntityH\x00R\x06entity\x12F\n" +
	"\brelation\x18\x03 \x01(\v2(.typedb.protocol.Migration.Item.RelationH\x00R\brelation\x12@\n" +
	"\x06header\x18\x0f \x01(\v2&.typedb.protocol.Migration.Item.HeaderH\x00R\x06header\x12I\n" +
	"\tchecksums\x18\x10 \x01(\v2).typedb.protocol.Migration.Item.ChecksumsH\x00R\tchecksums\x1a~\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12N\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2..typedb.protocol.Migration.Item.OwnedAttributeR\n" +
	"attributes\x1a\xc2\x01\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12N\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2..typedb.protocol.Migration.Item.OwnedAttributeR\n" +
	"attributes\x12?\n" +
	"\x05value\x18\x04 \x01(\v2).typedb.protocol.Migration.MigrationValueR\x05value\x1a\xce\x02\n" +
	"\bRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12N\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2..typedb.protocol.Migration.Item.OwnedAttributeR\n" +
	"attributes\x12C\n" +
	"\x05roles\x18\x04 \x03(\v2-.typedb.protocol.Migration.Item.Relation.RoleR\x05roles\x1a\x86\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12N\n" +
	"\aplayers\x18\x02 \x03(\v24.typedb.protocol.Migration.Item.Relation.Role.PlayerR\aplayers\x1a\x18\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a \n" +
	"\x0eOwnedAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a\\\n" +
	"\x06Header\x12%\n" +
	"\x0etypedb_version\x18\x01 \x01(\tR\rtypedbVersion\x12+\n" +
	"\x11original_database\x18\x02 \x01(\tR\x10originalDatabase\x1a\xcc\x01\n" +
	"\tChecksums\x12!\n" +
	"\fentity_count\x18\x01 \x01(\x03R\ventityCount\x12'\n" +
	"\x0fattribute_count\x18\x02 \x01(\x03R\x0eattributeCount\x12%\n" +
	"\x0erelation_count\x18\x03 \x01(\x03R\rrelationCount\x12\x1d\n" +
	"\n" +
	"role_count\x18\x04 \x01(\x03R\troleCount\x12'\n" +
	"\x0fownership_count\x18\x05 \x01(\x03R\x0eownershipCountJ\x04\b\x06\x10\aB\x06\n" +
	"\x04item\x1a\x9d\x04\n" +
	"\x0eMigrationValue\x12\x18\n" +
	"\x06string\x18\x01 \x01(\tH\x00R\x06string\x12\x1a\n" +
	"\aboolean\x18\x02 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x03 \x01(\x03H\x00R\ainteger\x12\x18\n" +
	"\x06double\x18\x04 \x01(\x01H\x00R\x06double\x12)\n" +
	"\x0fdatetime_millis\x18\x05 \x01(\x03H\x00R\x0edatetimeMillis\x12:\n" +
	"\adecimal\x18\x06 \x01(\v2\x1e.typedb.protocol.Value.DecimalH\x00R\adecimal\x121\n" +
	"\x04date\x18\b \x01(\v2\x1b.typedb.protocol.Value.DateH\x00R\x04date\x12=\n" +
	"\bdatetime\x18\t \x01(\v2\x1f.typedb.protocol.Value.DatetimeH\x00R\bdatetime\x12E\n" +
	"\vdatetime_tz\x18\n" +
	" \x01(\v2\".typedb.protocol.Value.Datetime_TZH\x00R\n" +
	"datetimeTz\x12=\n" +
	"\bduration\x18\v \x01(\v2\x1f.typedb.protocol.Value.DurationH\x00R\bduration\x127\n" +
	"\x06struct\x18\f \x01(\v2\x1d.typedb.protocol.Value.StructH\x00R\x06structB\a\n" +
	"\x05valueBCZAgithub.com/mcp-software-think-execute-server/go-typedb-v3-grpc/pbb\x06proto3"

var (
	file_proto_migration_proto_rawDescOnce sync.Once
	file_proto_migration_proto_rawDescData []byte
)

func file_proto_migration_proto_rawDescGZIP() []byte {
	file_proto_migration_proto_rawDescOnce.Do(func() {
		file_proto_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_migration_proto_rawDesc), len(file_proto_migration_proto_rawDesc)))
	})
	return file_proto_migration_proto_rawDescData
}

var file_proto_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_migration_proto_goTypes = []any{
	(*Migration)(nil),                           // 0: typedb.protocol.Migration
	(*Migration_Export)(nil),                    // 1: typedb.protocol.Migration.Export
	(*Migration_Import)(nil),                    // 2: typedb.protocol.Migration.Import
	(*Migration_Item)(nil),                      // 3: typedb.protocol.Migration.Item
	(*Migration_MigrationValue)(nil),            // 4: typedb.protocol.Migration.MigrationValue
	(*Migration_Export_Req)(nil),                // 5: typedb.protocol.Migration.Export.Req
	(*Migration_Export_Server)(nil),             // 6: typedb.protocol.Migration.Export.Server
	(*Migration_Export_InitialRes)(nil),         // 7: typedb.protocol.Migration.Export.InitialRes
	(*Migration_Export_ResPart)(nil),            // 8: typedb.protocol.Migration.Export.ResPart
	(*Migration_Export_Done)(nil),               // 9: typedb.protocol.Migration.Export.Done
	(*Migration_Import_Client)(nil),             // 10: typedb.protocol.Migration.Import.Client
	(*Migration_Import_Server)(nil),             // 11: typedb.protocol.Migration.Import.Server
	(*Migration_Import_Client_InitialReq)(nil),  // 12: typedb.protocol.Migration.Import.Client.InitialReq
	(*Migration_Import_Client_ReqPart)(nil),     // 13: typedb.protocol.Migration.Import.Client.ReqPart
	(*Migration_Import_Client_Done)(nil),        // 14: typedb.protocol.Migration.Import.Client.Done
	(*Migration_Import_Server_Done)(nil),        // 15: typedb.protocol.Migration.Import.Server.Done
	(*Migration_Item_Entity)(nil),               // 16: typedb.protocol.Migration.Item.Entity
	(*Migration_Item_Attribute)(nil),            // 17: typedb.protocol.Migration.Item.Attribute
	(*Migration_Item_Relation)(nil),             // 18: typedb.protocol.Migration.Item.Relation
	(*Migration_Item_OwnedAttribute)(nil),       // 19: typedb.protocol.Migration.Item.OwnedAttribute
	(*Migration_Item_Header)(nil),               // 20: typedb.protocol.Migration.Item.Header
	(*Migration_Item_Checksums)(nil),            // 21: typedb.protocol.Migration.Item.Checksums
	(*Migration_Item_Relation_Role)(nil),        // 22: typedb.protocol.Migration.Item.Relation.Role
	(*Migration_Item_Relation_Role_Player)(nil), // 23: typedb.protocol.Migration.Item.Relation.Role.Player
	(*Value_Decimal)(nil),                       // 24: typedb.protocol.Value.Decimal
	(*Value_Date)(nil),                          // 25: typedb.protocol.Value.Date
	(*Value_Datetime)(nil),                      // 26: typedb.protocol.Value.Datetime
	(*Value_Datetime_TZ)(nil),                   // 27: typedb.protocol.Value.Datetime_TZ
	(*Value_Duration)(nil),                      // 28: typedb.protocol.Value.Duration
	(*Value_Struct)(nil),                        // 29: typedb.protocol.Value.Struct
}
var file_proto_migration_proto_depIdxs = []int32{
	17, // 0: typedb.protocol.Migration.Item.attribute:type_name -> typedb.protocol.Migration.Item.Attribute
	16, // 1: typedb.protocol.Migration.Item.entity:type_name -> typedb.protocol.Migration.Item.Entity
	18, // 2: typedb.protocol.Migration.Item.relation:type_name -> typedb.protocol.Migration.Item.Relation
	20, // 3: typedb.protocol.Migration.Item.header:type_name -> typedb.protocol.Migration.Item.Header
	21, // 4: typedb.protocol.Migration.Item.checksums:type_name -> typedb.protocol.Migration.Item.Checksums
	24, // 5: typedb.protocol.Migration.MigrationValue.decimal:type_name -> typedb.protocol.Value.Decimal
	25, // 6: typedb.protocol.Migration.MigrationValue.date:type_name -> typedb.protocol.Value.Date
	26, // 7: typedb.protocol.Migration.MigrationValue.datetime:type_name -> typedb.protocol.Value.Datetime
	27, // 8: typedb.protocol.Migration.MigrationValue.datetime_tz:type_name -> typedb.protocol.Value.Datetime_TZ
	28, // 9: typedb.protocol.Migration.MigrationValue.duration:type_name -> typedb.protocol.Value.Duration
	29, // 10: typedb.protocol.Migration.MigrationValue.struct:type_name -> typedb.protocol.Value.Struct
	7,  // 11: typedb.protocol.Migration.Export.Server.initial_res:type_name -> typedb.protocol.Migration.Export.InitialRes
	8,  // 12: typedb.protocol.Migration.Export.Server.res_part:type_name -> typedb.protocol.Migration.Export.ResPart
	9,  // 13: typedb.protocol.Migration.Export.Server.done:type_name -> typedb.protocol.Migration.Export.Done
	3,  // 14: typedb.protocol.Migration.Export.ResPart.items:type_name -> typedb.protocol.Migration.Item
	12, // 15: typedb.protocol.Migration.Import.Client.initial_req:type_name -> typedb.protocol.Migration.Import.Client.InitialReq
	13, // 16: typedb.protocol.Migration.Import.Client.req_part:type_name -> typedb.protocol.Migration.Import.Client.ReqPart
	14, // 17: typedb.protocol.Migration.Import.Client.done:type_name -> typedb.protocol.Migration.Import.Client.Done
	15, // 18: typedb.protocol.Migration.Import.Server.done:type_name -> typedb.protocol.Migration.Import.Server.Done
	3,  // 19: typedb.protocol.Migration.Import.Client.ReqPart.items:type_name -> typedb.protocol.Migration.Item
	19, // 20: typedb.protocol.Migration.Item.Entity.attributes:type_name -> typedb.protocol.Migration.Item.OwnedAttribute
	19, // 21: typedb.protocol.Migration.Item.Attribute.attributes:type_name -> typedb.protocol.Migration.Item.OwnedAttribute
	4,  // 22: typedb.protocol.Migration.Item.Attribute.value:type_name -> typedb.protocol.Migration.MigrationValue
	19, // 23: typedb.protocol.Migration.Item.Relation.attributes:type_name -> typedb.protocol.Migration.Item.OwnedAttribute
	22, // 24: typedb.protocol.Migration.Item.Relation.roles:type_name -> typedb.protocol.Migration.Item.Relation.Role
	23, // 25: typedb.protocol.Migration.Item.Relation.Role.players:type_name -> typedb.protocol.Migration.Item.Relation.Role.Player
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_migration_proto_init() }
func file_proto_migration_proto_init() {
	if File_proto_migration_proto != nil {
		return
	}
	file_proto_concept_proto_init()
	file_proto_migration_proto_msgTypes[3].OneofWrappers = []any{
		(*Migration_Item_Attribute_)(nil),
		(*Migration_Item_Entity_)(nil),
		(*Migration_Item_Relation_)(nil),
		(*Migration_Item_Header_)(nil),
		(*Migration_Item_Checksums_)(nil),
	}
	file_proto_migration_proto_msgTypes[4].OneofWrappers = []any{
		(*Migration_MigrationValue_String_)(nil),
		(*Migration_MigrationValue_Boolean)(nil),
		(*Migration_MigrationValue_Integer)(nil),
		(*Migration_MigrationValue_Double)(nil),
		(*Migration_MigrationValue_DatetimeMillis)(nil),
		(*Migration_MigrationValue_Decimal)(nil),
		(*Migration_MigrationValue_Date)(nil),
		(*Migration_MigrationValue_Datetime)(nil),
		(*Migration_MigrationValue_DatetimeTz)(nil),
		(*Migration_MigrationValue_Duration)(nil),
		(*Migration_MigrationValue_Struct)(nil),
	}
	file_proto_migration_proto_msgTypes[6].OneofWrappers = []any{
		(*Migration_Export_Server_InitialRes)(nil),
		(*Migration_Export_Server_ResPart)(nil),
		(*Migration_Export_Server_Done)(nil),
	}
	file_proto_migration_proto_msgTypes[10].OneofWrappers = []any{
		(*Migration_Import_Client_InitialReq_)(nil),
		(*Migration_Import_Client_ReqPart_)(nil),
		(*Migration_Import_Client_Done_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_migration_proto_rawDesc), len(file_proto_migration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_migration_proto_goTypes,
		DependencyIndexes: file_proto_migration_proto_depIdxs,
		MessageInfos:      file_proto_migration_proto_msgTypes,
	}.Build()
	File_proto_migration_proto = out.File
	file_proto_migration_proto_goTypes = nil
	file_proto_migration_proto_depIdxs = nil
}
