// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: options.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{0}
}

type Options_Transaction struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Parallel                       *bool                  `protobuf:"varint,1,opt,name=parallel,proto3,oneof" json:"parallel,omitempty"`
	TransactionTimeoutMillis       *uint64                `protobuf:"varint,2,opt,name=transaction_timeout_millis,json=transactionTimeoutMillis,proto3,oneof" json:"transaction_timeout_millis,omitempty"`
	SchemaLockAcquireTimeoutMillis *uint64                `protobuf:"varint,3,opt,name=schema_lock_acquire_timeout_millis,json=schemaLockAcquireTimeoutMillis,proto3,oneof" json:"schema_lock_acquire_timeout_millis,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Options_Transaction) Reset() {
	*x = Options_Transaction{}
	mi := &file_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Transaction) ProtoMessage() {}

func (x *Options_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Transaction.ProtoReflect.Descriptor instead.
func (*Options_Transaction) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Options_Transaction) GetParallel() bool {
	if x != nil && x.Parallel != nil {
		return *x.Parallel
	}
	return false
}

func (x *Options_Transaction) GetTransactionTimeoutMillis() uint64 {
	if x != nil && x.TransactionTimeoutMillis != nil {
		return *x.TransactionTimeoutMillis
	}
	return 0
}

func (x *Options_Transaction) GetSchemaLockAcquireTimeoutMillis() uint64 {
	if x != nil && x.SchemaLockAcquireTimeoutMillis != nil {
		return *x.SchemaLockAcquireTimeoutMillis
	}
	return 0
}

type Options_Query struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IncludeInstanceTypes *bool                  `protobuf:"varint,1,opt,name=include_instance_types,json=includeInstanceTypes,proto3,oneof" json:"include_instance_types,omitempty"`
	PrefetchSize         *uint64                `protobuf:"varint,2,opt,name=prefetch_size,json=prefetchSize,proto3,oneof" json:"prefetch_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Options_Query) Reset() {
	*x = Options_Query{}
	mi := &file_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Query) ProtoMessage() {}

func (x *Options_Query) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Query.ProtoReflect.Descriptor instead.
func (*Options_Query) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Options_Query) GetIncludeInstanceTypes() bool {
	if x != nil && x.IncludeInstanceTypes != nil {
		return *x.IncludeInstanceTypes
	}
	return false
}

func (x *Options_Query) GetPrefetchSize() uint64 {
	if x != nil && x.PrefetchSize != nil {
		return *x.PrefetchSize
	}
	return 0
}

var File_options_proto protoreflect.FileDescriptor

const file_options_proto_rawDesc = "" +
	"\n" +
	"\roptions.proto\x12\x0ftypedb.protocol\"\xbd\x03\n" +
	"\aOptions\x1a\x95\x02\n" +
	"\vTransaction\x12\x1f\n" +
	"\bparallel\x18\x01 \x01(\bH\x00R\bparallel\x88\x01\x01\x12A\n" +
	"\x1atransaction_timeout_millis\x18\x02 \x01(\x04H\x01R\x18transactionTimeoutMillis\x88\x01\x01\x12O\n" +
	"\"schema_lock_acquire_timeout_millis\x18\x03 \x01(\x04H\x02R\x1eschemaLockAcquireTimeoutMillis\x88\x01\x01B\v\n" +
	"\t_parallelB\x1d\n" +
	"\x1b_transaction_timeout_millisB%\n" +
	"#_schema_lock_acquire_timeout_millis\x1a\x99\x01\n" +
	"\x05Query\x129\n" +
	"\x16include_instance_types\x18\x01 \x01(\bH\x00R\x14includeInstanceTypes\x88\x01\x01\x12(\n" +
	"\rprefetch_size\x18\x02 \x01(\x04H\x01R\fprefetchSize\x88\x01\x01B\x19\n" +
	"\x17_include_instance_typesB\x10\n" +
	"\x0e_prefetch_sizeB1Z/github.com/joycheney/go-typedb-v3-grpc/pb/protob\x06proto3"

var (
	file_options_proto_rawDescOnce sync.Once
	file_options_proto_rawDescData []byte
)

func file_options_proto_rawDescGZIP() []byte {
	file_options_proto_rawDescOnce.Do(func() {
		file_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_options_proto_rawDesc), len(file_options_proto_rawDesc)))
	})
	return file_options_proto_rawDescData
}

var file_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_options_proto_goTypes = []any{
	(*Options)(nil),             // 0: typedb.protocol.Options
	(*Options_Transaction)(nil), // 1: typedb.protocol.Options.Transaction
	(*Options_Query)(nil),       // 2: typedb.protocol.Options.Query
}
var file_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_proto_init() }
func file_options_proto_init() {
	if File_options_proto != nil {
		return
	}
	file_options_proto_msgTypes[1].OneofWrappers = []any{}
	file_options_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_proto_rawDesc), len(file_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_options_proto_goTypes,
		DependencyIndexes: file_options_proto_depIdxs,
		MessageInfos:      file_options_proto_msgTypes,
	}.Build()
	File_options_proto = out.File
	file_options_proto_goTypes = nil
	file_options_proto_depIdxs = nil
}
