// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction_Type int32

const (
	Transaction_READ   Transaction_Type = 0
	Transaction_WRITE  Transaction_Type = 1
	Transaction_SCHEMA Transaction_Type = 2
)

// Enum value maps for Transaction_Type.
var (
	Transaction_Type_name = map[int32]string{
		0: "READ",
		1: "WRITE",
		2: "SCHEMA",
	}
	Transaction_Type_value = map[string]int32{
		"READ":   0,
		"WRITE":  1,
		"SCHEMA": 2,
	}
)

func (x Transaction_Type) Enum() *Transaction_Type {
	p := new(Transaction_Type)
	*p = x
	return p
}

func (x Transaction_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (Transaction_Type) Type() protoreflect.EnumType {
	return &file_proto_transaction_proto_enumTypes[0]
}

func (x Transaction_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_Type.Descriptor instead.
func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

type Transaction_Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqs          []*Transaction_Req     `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Client) Reset() {
	*x = Transaction_Client{}
	mi := &file_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Client) ProtoMessage() {}

func (x *Transaction_Client) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Client.ProtoReflect.Descriptor instead.
func (*Transaction_Client) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transaction_Client) GetReqs() []*Transaction_Req {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type Transaction_Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Server:
	//
	//	*Transaction_Server_Res
	//	*Transaction_Server_ResPart
	Server        isTransaction_Server_Server `protobuf_oneof:"server"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Server) Reset() {
	*x = Transaction_Server{}
	mi := &file_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Server) ProtoMessage() {}

func (x *Transaction_Server) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Server.ProtoReflect.Descriptor instead.
func (*Transaction_Server) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Transaction_Server) GetServer() isTransaction_Server_Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Transaction_Server) GetRes() *Transaction_Res {
	if x != nil {
		if x, ok := x.Server.(*Transaction_Server_Res); ok {
			return x.Res
		}
	}
	return nil
}

func (x *Transaction_Server) GetResPart() *Transaction_ResPart {
	if x != nil {
		if x, ok := x.Server.(*Transaction_Server_ResPart); ok {
			return x.ResPart
		}
	}
	return nil
}

type isTransaction_Server_Server interface {
	isTransaction_Server_Server()
}

type Transaction_Server_Res struct {
	Res *Transaction_Res `protobuf:"bytes,1,opt,name=res,proto3,oneof"`
}

type Transaction_Server_ResPart struct {
	ResPart *Transaction_ResPart `protobuf:"bytes,2,opt,name=res_part,json=resPart,proto3,oneof"`
}

func (*Transaction_Server_Res) isTransaction_Server_Server() {}

func (*Transaction_Server_ResPart) isTransaction_Server_Server() {}

type Transaction_Req struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ReqId    []byte                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Req:
	//
	//	*Transaction_Req_OpenReq
	//	*Transaction_Req_QueryReq
	//	*Transaction_Req_StreamReq
	//	*Transaction_Req_CommitReq
	//	*Transaction_Req_RollbackReq
	//	*Transaction_Req_CloseReq
	Req           isTransaction_Req_Req `protobuf_oneof:"req"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Req) Reset() {
	*x = Transaction_Req{}
	mi := &file_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Req) ProtoMessage() {}

func (x *Transaction_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Req.ProtoReflect.Descriptor instead.
func (*Transaction_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Transaction_Req) GetReqId() []byte {
	if x != nil {
		return x.ReqId
	}
	return nil
}

func (x *Transaction_Req) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction_Req) GetReq() isTransaction_Req_Req {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *Transaction_Req) GetOpenReq() *Transaction_Open_Req {
	if x != nil {
		if x, ok := x.Req.(*Transaction_Req_OpenReq); ok {
			return x.OpenReq
		}
	}
	return nil
}

func (x *Transaction_Req) GetQueryReq() *Query_Req {
	if x != nil {
		if x, ok := x.Req.(*Transaction_Req_QueryReq); ok {
			return x.QueryReq
		}
	}
	return nil
}

func (x *Transaction_Req) GetStreamReq() *Transaction_StreamSignal_Req {
	if x != nil {
		if x, ok := x.Req.(*Transaction_Req_StreamReq); ok {
			return x.StreamReq
		}
	}
	return nil
}

func (x *Transaction_Req) GetCommitReq() *Transaction_Commit_Req {
	if x != nil {
		if x, ok := x.Req.(*Transaction_Req_CommitReq); ok {
			return x.CommitReq
		}
	}
	return nil
}

func (x *Transaction_Req) GetRollbackReq() *Transaction_Rollback_Req {
	if x != nil {
		if x, ok := x.Req.(*Transaction_Req_RollbackReq); ok {
			return x.RollbackReq
		}
	}
	return nil
}

func (x *Transaction_Req) GetCloseReq() *Transaction_Close_Req {
	if x != nil {
		if x, ok := x.Req.(*Transaction_Req_CloseReq); ok {
			return x.CloseReq
		}
	}
	return nil
}

type isTransaction_Req_Req interface {
	isTransaction_Req_Req()
}

type Transaction_Req_OpenReq struct {
	OpenReq *Transaction_Open_Req `protobuf:"bytes,3,opt,name=open_req,json=openReq,proto3,oneof"`
}

type Transaction_Req_QueryReq struct {
	QueryReq *Query_Req `protobuf:"bytes,4,opt,name=query_req,json=queryReq,proto3,oneof"`
}

type Transaction_Req_StreamReq struct {
	StreamReq *Transaction_StreamSignal_Req `protobuf:"bytes,5,opt,name=stream_req,json=streamReq,proto3,oneof"`
}

type Transaction_Req_CommitReq struct {
	CommitReq *Transaction_Commit_Req `protobuf:"bytes,6,opt,name=commit_req,json=commitReq,proto3,oneof"`
}

type Transaction_Req_RollbackReq struct {
	RollbackReq *Transaction_Rollback_Req `protobuf:"bytes,7,opt,name=rollback_req,json=rollbackReq,proto3,oneof"`
}

type Transaction_Req_CloseReq struct {
	CloseReq *Transaction_Close_Req `protobuf:"bytes,8,opt,name=close_req,json=closeReq,proto3,oneof"`
}

func (*Transaction_Req_OpenReq) isTransaction_Req_Req() {}

func (*Transaction_Req_QueryReq) isTransaction_Req_Req() {}

func (*Transaction_Req_StreamReq) isTransaction_Req_Req() {}

func (*Transaction_Req_CommitReq) isTransaction_Req_Req() {}

func (*Transaction_Req_RollbackReq) isTransaction_Req_Req() {}

func (*Transaction_Req_CloseReq) isTransaction_Req_Req() {}

type Transaction_Res struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId []byte                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	// Types that are valid to be assigned to Res:
	//
	//	*Transaction_Res_OpenRes
	//	*Transaction_Res_QueryInitialRes
	//	*Transaction_Res_CommitRes
	//	*Transaction_Res_RollbackRes
	Res           isTransaction_Res_Res `protobuf_oneof:"res"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Res) Reset() {
	*x = Transaction_Res{}
	mi := &file_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Res) ProtoMessage() {}

func (x *Transaction_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Res.ProtoReflect.Descriptor instead.
func (*Transaction_Res) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Transaction_Res) GetReqId() []byte {
	if x != nil {
		return x.ReqId
	}
	return nil
}

func (x *Transaction_Res) GetRes() isTransaction_Res_Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *Transaction_Res) GetOpenRes() *Transaction_Open_Res {
	if x != nil {
		if x, ok := x.Res.(*Transaction_Res_OpenRes); ok {
			return x.OpenRes
		}
	}
	return nil
}

func (x *Transaction_Res) GetQueryInitialRes() *Query_InitialRes {
	if x != nil {
		if x, ok := x.Res.(*Transaction_Res_QueryInitialRes); ok {
			return x.QueryInitialRes
		}
	}
	return nil
}

func (x *Transaction_Res) GetCommitRes() *Transaction_Commit_Res {
	if x != nil {
		if x, ok := x.Res.(*Transaction_Res_CommitRes); ok {
			return x.CommitRes
		}
	}
	return nil
}

func (x *Transaction_Res) GetRollbackRes() *Transaction_Rollback_Res {
	if x != nil {
		if x, ok := x.Res.(*Transaction_Res_RollbackRes); ok {
			return x.RollbackRes
		}
	}
	return nil
}

type isTransaction_Res_Res interface {
	isTransaction_Res_Res()
}

type Transaction_Res_OpenRes struct {
	OpenRes *Transaction_Open_Res `protobuf:"bytes,2,opt,name=open_res,json=openRes,proto3,oneof"`
}

type Transaction_Res_QueryInitialRes struct {
	QueryInitialRes *Query_InitialRes `protobuf:"bytes,3,opt,name=query_initial_res,json=queryInitialRes,proto3,oneof"`
}

type Transaction_Res_CommitRes struct {
	CommitRes *Transaction_Commit_Res `protobuf:"bytes,5,opt,name=commit_res,json=commitRes,proto3,oneof"`
}

type Transaction_Res_RollbackRes struct {
	RollbackRes *Transaction_Rollback_Res `protobuf:"bytes,6,opt,name=rollback_res,json=rollbackRes,proto3,oneof"`
}

func (*Transaction_Res_OpenRes) isTransaction_Res_Res() {}

func (*Transaction_Res_QueryInitialRes) isTransaction_Res_Res() {}

func (*Transaction_Res_CommitRes) isTransaction_Res_Res() {}

func (*Transaction_Res_RollbackRes) isTransaction_Res_Res() {}

type Transaction_ResPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId []byte                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	// Types that are valid to be assigned to ResPart:
	//
	//	*Transaction_ResPart_QueryRes
	//	*Transaction_ResPart_StreamRes
	ResPart       isTransaction_ResPart_ResPart `protobuf_oneof:"res_part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_ResPart) Reset() {
	*x = Transaction_ResPart{}
	mi := &file_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_ResPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_ResPart) ProtoMessage() {}

func (x *Transaction_ResPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_ResPart.ProtoReflect.Descriptor instead.
func (*Transaction_ResPart) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Transaction_ResPart) GetReqId() []byte {
	if x != nil {
		return x.ReqId
	}
	return nil
}

func (x *Transaction_ResPart) GetResPart() isTransaction_ResPart_ResPart {
	if x != nil {
		return x.ResPart
	}
	return nil
}

func (x *Transaction_ResPart) GetQueryRes() *Query_ResPart {
	if x != nil {
		if x, ok := x.ResPart.(*Transaction_ResPart_QueryRes); ok {
			return x.QueryRes
		}
	}
	return nil
}

func (x *Transaction_ResPart) GetStreamRes() *Transaction_StreamSignal_ResPart {
	if x != nil {
		if x, ok := x.ResPart.(*Transaction_ResPart_StreamRes); ok {
			return x.StreamRes
		}
	}
	return nil
}

type isTransaction_ResPart_ResPart interface {
	isTransaction_ResPart_ResPart()
}

type Transaction_ResPart_QueryRes struct {
	QueryRes *Query_ResPart `protobuf:"bytes,2,opt,name=query_res,json=queryRes,proto3,oneof"`
}

type Transaction_ResPart_StreamRes struct {
	StreamRes *Transaction_StreamSignal_ResPart `protobuf:"bytes,3,opt,name=stream_res,json=streamRes,proto3,oneof"`
}

func (*Transaction_ResPart_QueryRes) isTransaction_ResPart_ResPart() {}

func (*Transaction_ResPart_StreamRes) isTransaction_ResPart_ResPart() {}

type Transaction_Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Open) Reset() {
	*x = Transaction_Open{}
	mi := &file_proto_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Open) ProtoMessage() {}

func (x *Transaction_Open) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Open.ProtoReflect.Descriptor instead.
func (*Transaction_Open) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 5}
}

type Transaction_Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Commit) Reset() {
	*x = Transaction_Commit{}
	mi := &file_proto_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Commit) ProtoMessage() {}

func (x *Transaction_Commit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Commit.ProtoReflect.Descriptor instead.
func (*Transaction_Commit) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 6}
}

type Transaction_Rollback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Rollback) Reset() {
	*x = Transaction_Rollback{}
	mi := &file_proto_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Rollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Rollback) ProtoMessage() {}

func (x *Transaction_Rollback) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Rollback.ProtoReflect.Descriptor instead.
func (*Transaction_Rollback) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 7}
}

type Transaction_Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Close) Reset() {
	*x = Transaction_Close{}
	mi := &file_proto_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Close) ProtoMessage() {}

func (x *Transaction_Close) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Close.ProtoReflect.Descriptor instead.
func (*Transaction_Close) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 8}
}

type Transaction_GetSchemaExceptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_GetSchemaExceptions) Reset() {
	*x = Transaction_GetSchemaExceptions{}
	mi := &file_proto_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_GetSchemaExceptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_GetSchemaExceptions) ProtoMessage() {}

func (x *Transaction_GetSchemaExceptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_GetSchemaExceptions.ProtoReflect.Descriptor instead.
func (*Transaction_GetSchemaExceptions) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 9}
}

type Transaction_SchemaException struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_SchemaException) Reset() {
	*x = Transaction_SchemaException{}
	mi := &file_proto_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_SchemaException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_SchemaException) ProtoMessage() {}

func (x *Transaction_SchemaException) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_SchemaException.ProtoReflect.Descriptor instead.
func (*Transaction_SchemaException) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Transaction_SchemaException) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Transaction_SchemaException) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Transaction_StreamSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_StreamSignal) Reset() {
	*x = Transaction_StreamSignal{}
	mi := &file_proto_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_StreamSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_StreamSignal) ProtoMessage() {}

func (x *Transaction_StreamSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_StreamSignal.ProtoReflect.Descriptor instead.
func (*Transaction_StreamSignal) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 11}
}

type Transaction_Open_Req struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Database             string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Type                 Transaction_Type       `protobuf:"varint,2,opt,name=type,proto3,enum=typedb.protocol.Transaction_Type" json:"type,omitempty"`
	Options              *Options_Transaction   `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	NetworkLatencyMillis uint64                 `protobuf:"varint,4,opt,name=network_latency_millis,json=networkLatencyMillis,proto3" json:"network_latency_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction_Open_Req) Reset() {
	*x = Transaction_Open_Req{}
	mi := &file_proto_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Open_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Open_Req) ProtoMessage() {}

func (x *Transaction_Open_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Open_Req.ProtoReflect.Descriptor instead.
func (*Transaction_Open_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *Transaction_Open_Req) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Transaction_Open_Req) GetType() Transaction_Type {
	if x != nil {
		return x.Type
	}
	return Transaction_READ
}

func (x *Transaction_Open_Req) GetOptions() *Options_Transaction {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Transaction_Open_Req) GetNetworkLatencyMillis() uint64 {
	if x != nil {
		return x.NetworkLatencyMillis
	}
	return 0
}

type Transaction_Open_Res struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerDurationMillis uint64                 `protobuf:"varint,2,opt,name=server_duration_millis,json=serverDurationMillis,proto3" json:"server_duration_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction_Open_Res) Reset() {
	*x = Transaction_Open_Res{}
	mi := &file_proto_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Open_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Open_Res) ProtoMessage() {}

func (x *Transaction_Open_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Open_Res.ProtoReflect.Descriptor instead.
func (*Transaction_Open_Res) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 5, 1}
}

func (x *Transaction_Open_Res) GetServerDurationMillis() uint64 {
	if x != nil {
		return x.ServerDurationMillis
	}
	return 0
}

type Transaction_Commit_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Commit_Req) Reset() {
	*x = Transaction_Commit_Req{}
	mi := &file_proto_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Commit_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Commit_Req) ProtoMessage() {}

func (x *Transaction_Commit_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Commit_Req.ProtoReflect.Descriptor instead.
func (*Transaction_Commit_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 6, 0}
}

type Transaction_Commit_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Commit_Res) Reset() {
	*x = Transaction_Commit_Res{}
	mi := &file_proto_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Commit_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Commit_Res) ProtoMessage() {}

func (x *Transaction_Commit_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Commit_Res.ProtoReflect.Descriptor instead.
func (*Transaction_Commit_Res) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 6, 1}
}

type Transaction_Rollback_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Rollback_Req) Reset() {
	*x = Transaction_Rollback_Req{}
	mi := &file_proto_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Rollback_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Rollback_Req) ProtoMessage() {}

func (x *Transaction_Rollback_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Rollback_Req.ProtoReflect.Descriptor instead.
func (*Transaction_Rollback_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 7, 0}
}

type Transaction_Rollback_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Rollback_Res) Reset() {
	*x = Transaction_Rollback_Res{}
	mi := &file_proto_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Rollback_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Rollback_Res) ProtoMessage() {}

func (x *Transaction_Rollback_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Rollback_Res.ProtoReflect.Descriptor instead.
func (*Transaction_Rollback_Res) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 7, 1}
}

type Transaction_Close_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Close_Req) Reset() {
	*x = Transaction_Close_Req{}
	mi := &file_proto_transaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Close_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Close_Req) ProtoMessage() {}

func (x *Transaction_Close_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Close_Req.ProtoReflect.Descriptor instead.
func (*Transaction_Close_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 8, 0}
}

type Transaction_Close_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Close_Res) Reset() {
	*x = Transaction_Close_Res{}
	mi := &file_proto_transaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Close_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Close_Res) ProtoMessage() {}

func (x *Transaction_Close_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Close_Res.ProtoReflect.Descriptor instead.
func (*Transaction_Close_Res) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 8, 1}
}

type Transaction_GetSchemaExceptions_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_GetSchemaExceptions_Req) Reset() {
	*x = Transaction_GetSchemaExceptions_Req{}
	mi := &file_proto_transaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_GetSchemaExceptions_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_GetSchemaExceptions_Req) ProtoMessage() {}

func (x *Transaction_GetSchemaExceptions_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_GetSchemaExceptions_Req.ProtoReflect.Descriptor instead.
func (*Transaction_GetSchemaExceptions_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 9, 0}
}

type Transaction_GetSchemaExceptions_Res struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Exceptions    []*Transaction_SchemaException `protobuf:"bytes,1,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_GetSchemaExceptions_Res) Reset() {
	*x = Transaction_GetSchemaExceptions_Res{}
	mi := &file_proto_transaction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_GetSchemaExceptions_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_GetSchemaExceptions_Res) ProtoMessage() {}

func (x *Transaction_GetSchemaExceptions_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_GetSchemaExceptions_Res.ProtoReflect.Descriptor instead.
func (*Transaction_GetSchemaExceptions_Res) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 9, 1}
}

func (x *Transaction_GetSchemaExceptions_Res) GetExceptions() []*Transaction_SchemaException {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

type Transaction_StreamSignal_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_StreamSignal_Req) Reset() {
	*x = Transaction_StreamSignal_Req{}
	mi := &file_proto_transaction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_StreamSignal_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_StreamSignal_Req) ProtoMessage() {}

func (x *Transaction_StreamSignal_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_StreamSignal_Req.ProtoReflect.Descriptor instead.
func (*Transaction_StreamSignal_Req) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 11, 0}
}

type Transaction_StreamSignal_ResPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*Transaction_StreamSignal_ResPart_Continue_
	//	*Transaction_StreamSignal_ResPart_Done_
	//	*Transaction_StreamSignal_ResPart_Error
	State         isTransaction_StreamSignal_ResPart_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_StreamSignal_ResPart) Reset() {
	*x = Transaction_StreamSignal_ResPart{}
	mi := &file_proto_transaction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_StreamSignal_ResPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_StreamSignal_ResPart) ProtoMessage() {}

func (x *Transaction_StreamSignal_ResPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_StreamSignal_ResPart.ProtoReflect.Descriptor instead.
func (*Transaction_StreamSignal_ResPart) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 11, 1}
}

func (x *Transaction_StreamSignal_ResPart) GetState() isTransaction_StreamSignal_ResPart_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Transaction_StreamSignal_ResPart) GetContinue() *Transaction_StreamSignal_ResPart_Continue {
	if x != nil {
		if x, ok := x.State.(*Transaction_StreamSignal_ResPart_Continue_); ok {
			return x.Continue
		}
	}
	return nil
}

func (x *Transaction_StreamSignal_ResPart) GetDone() *Transaction_StreamSignal_ResPart_Done {
	if x != nil {
		if x, ok := x.State.(*Transaction_StreamSignal_ResPart_Done_); ok {
			return x.Done
		}
	}
	return nil
}

func (x *Transaction_StreamSignal_ResPart) GetError() *Error {
	if x != nil {
		if x, ok := x.State.(*Transaction_StreamSignal_ResPart_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTransaction_StreamSignal_ResPart_State interface {
	isTransaction_StreamSignal_ResPart_State()
}

type Transaction_StreamSignal_ResPart_Continue_ struct {
	Continue *Transaction_StreamSignal_ResPart_Continue `protobuf:"bytes,1,opt,name=continue,proto3,oneof"`
}

type Transaction_StreamSignal_ResPart_Done_ struct {
	Done *Transaction_StreamSignal_ResPart_Done `protobuf:"bytes,2,opt,name=done,proto3,oneof"`
}

type Transaction_StreamSignal_ResPart_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*Transaction_StreamSignal_ResPart_Continue_) isTransaction_StreamSignal_ResPart_State() {}

func (*Transaction_StreamSignal_ResPart_Done_) isTransaction_StreamSignal_ResPart_State() {}

func (*Transaction_StreamSignal_ResPart_Error) isTransaction_StreamSignal_ResPart_State() {}

type Transaction_StreamSignal_ResPart_Continue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_StreamSignal_ResPart_Continue) Reset() {
	*x = Transaction_StreamSignal_ResPart_Continue{}
	mi := &file_proto_transaction_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_StreamSignal_ResPart_Continue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_StreamSignal_ResPart_Continue) ProtoMessage() {}

func (x *Transaction_StreamSignal_ResPart_Continue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_StreamSignal_ResPart_Continue.ProtoReflect.Descriptor instead.
func (*Transaction_StreamSignal_ResPart_Continue) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 11, 1, 0}
}

type Transaction_StreamSignal_ResPart_Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_StreamSignal_ResPart_Done) Reset() {
	*x = Transaction_StreamSignal_ResPart_Done{}
	mi := &file_proto_transaction_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_StreamSignal_ResPart_Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_StreamSignal_ResPart_Done) ProtoMessage() {}

func (x *Transaction_StreamSignal_ResPart_Done) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_StreamSignal_ResPart_Done.ProtoReflect.Descriptor instead.
func (*Transaction_StreamSignal_ResPart_Done) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0, 11, 1, 1}
}

var File_proto_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x17proto/transaction.proto\x12\x0ftypedb.protocol\x1a\x11proto/error.proto\x1a\x13proto/options.proto\x1a\x11proto/query.proto\"\xa7\x11\n" +
	"\vTransaction\x1a>\n" +
	"\x06Client\x124\n" +
	"\x04reqs\x18\x01 \x03(\v2 .typedb.protocol.Transaction.ReqR\x04reqs\x1a\x8b\x01\n" +
	"\x06Server\x124\n" +
	"\x03res\x18\x01 \x01(\v2 .typedb.protocol.Transaction.ResH\x00R\x03res\x12A\n" +
	"\bres_part\x18\x02 \x01(\v2$.typedb.protocol.Transaction.ResPartH\x00R\aresPartB\b\n" +
	"\x06server\x1a\xdc\x04\n" +
	"\x03Req\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\fR\x05reqId\x12J\n" +
	"\bmetadata\x18\x02 \x03(\v2..typedb.protocol.Transaction.Req.MetadataEntryR\bmetadata\x12B\n" +
	"\bopen_req\x18\x03 \x01(\v2%.typedb.protocol.Transaction.Open.ReqH\x00R\aopenReq\x129\n" +
	"\tquery_req\x18\x04 \x01(\v2\x1a.typedb.protocol.Query.ReqH\x00R\bqueryReq\x12N\n" +
	"\n" +
	"stream_req\x18\x05 \x01(\v2-.typedb.protocol.Transaction.StreamSignal.ReqH\x00R\tstreamReq\x12H\n" +
	"\n" +
	"commit_req\x18\x06 \x01(\v2'.typedb.protocol.Transaction.Commit.ReqH\x00R\tcommitReq\x12N\n" +
	"\frollback_req\x18\a \x01(\v2).typedb.protocol.Transaction.Rollback.ReqH\x00R\vrollbackReq\x12E\n" +
	"\tclose_req\x18\b \x01(\v2&.typedb.protocol.Transaction.Close.ReqH\x00R\bcloseReq\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03req\x1a\xd2\x02\n" +
	"\x03Res\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\fR\x05reqId\x12B\n" +
	"\bopen_res\x18\x02 \x01(\v2%.typedb.protocol.Transaction.Open.ResH\x00R\aopenRes\x12O\n" +
	"\x11query_initial_res\x18\x03 \x01(\v2!.typedb.protocol.Query.InitialResH\x00R\x0fqueryInitialRes\x12H\n" +
	"\n" +
	"commit_res\x18\x05 \x01(\v2'.typedb.protocol.Transaction.Commit.ResH\x00R\tcommitRes\x12N\n" +
	"\frollback_res\x18\x06 \x01(\v2).typedb.protocol.Transaction.Rollback.ResH\x00R\vrollbackResB\x05\n" +
	"\x03res\x1a\xbf\x01\n" +
	"\aResPart\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\fR\x05reqId\x12=\n" +
	"\tquery_res\x18\x02 \x01(\v2\x1e.typedb.protocol.Query.ResPartH\x00R\bqueryRes\x12R\n" +
	"\n" +
	"stream_res\x18\x03 \x01(\v21.typedb.protocol.Transaction.StreamSignal.ResPartH\x00R\tstreamResB\n" +
	"\n" +
	"\bres_part\x1a\x94\x02\n" +
	"\x04Open\x1a\xce\x01\n" +
	"\x03Req\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.typedb.protocol.Transaction.TypeR\x04type\x12>\n" +
	"\aoptions\x18\x03 \x01(\v2$.typedb.protocol.Options.TransactionR\aoptions\x124\n" +
	"\x16network_latency_millis\x18\x04 \x01(\x04R\x14networkLatencyMillis\x1a;\n" +
	"\x03Res\x124\n" +
	"\x16server_duration_millis\x18\x02 \x01(\x04R\x14serverDurationMillis\x1a\x16\n" +
	"\x06Commit\x1a\x05\n" +
	"\x03Req\x1a\x05\n" +
	"\x03Res\x1a\x18\n" +
	"\bRollback\x1a\x05\n" +
	"\x03Req\x1a\x05\n" +
	"\x03Res\x1a\x15\n" +
	"\x05Close\x1a\x05\n" +
	"\x03Req\x1a\x05\n" +
	"\x03Res\x1aq\n" +
	"\x13GetSchemaExceptions\x1a\x05\n" +
	"\x03Req\x1aS\n" +
	"\x03Res\x12L\n" +
	"\n" +
	"exceptions\x18\x01 \x03(\v2,.typedb.protocol.Transaction.SchemaExceptionR\n" +
	"exceptions\x1a?\n" +
	"\x0fSchemaException\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x1a\x96\x02\n" +
	"\fStreamSignal\x1a\x05\n" +
	"\x03Req\x1a\xfe\x01\n" +
	"\aResPart\x12X\n" +
	"\bcontinue\x18\x01 \x01(\v2:.typedb.protocol.Transaction.StreamSignal.ResPart.ContinueH\x00R\bcontinue\x12L\n" +
	"\x04done\x18\x02 \x01(\v26.typedb.protocol.Transaction.StreamSignal.ResPart.DoneH\x00R\x04done\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x16.typedb.protocol.ErrorH\x00R\x05error\x1a\n" +
	"\n" +
	"\bContinue\x1a\x06\n" +
	"\x04DoneB\a\n" +
	"\x05state\"'\n" +
	"\x04Type\x12\b\n" +
	"\x04READ\x10\x00\x12\t\n" +
	"\x05WRITE\x10\x01\x12\n" +
	"\n" +
	"\x06SCHEMA\x10\x02BCZAgithub.com/joycheney/go-typedb-v3-grpc/pbb\x06proto3"

var (
	file_proto_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_proto_rawDescData []byte
)

func file_proto_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_proto_rawDescData
}

var file_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_transaction_proto_goTypes = []any{
	(Transaction_Type)(0),                             // 0: typedb.protocol.Transaction.Type
	(*Transaction)(nil),                               // 1: typedb.protocol.Transaction
	(*Transaction_Client)(nil),                        // 2: typedb.protocol.Transaction.Client
	(*Transaction_Server)(nil),                        // 3: typedb.protocol.Transaction.Server
	(*Transaction_Req)(nil),                           // 4: typedb.protocol.Transaction.Req
	(*Transaction_Res)(nil),                           // 5: typedb.protocol.Transaction.Res
	(*Transaction_ResPart)(nil),                       // 6: typedb.protocol.Transaction.ResPart
	(*Transaction_Open)(nil),                          // 7: typedb.protocol.Transaction.Open
	(*Transaction_Commit)(nil),                        // 8: typedb.protocol.Transaction.Commit
	(*Transaction_Rollback)(nil),                      // 9: typedb.protocol.Transaction.Rollback
	(*Transaction_Close)(nil),                         // 10: typedb.protocol.Transaction.Close
	(*Transaction_GetSchemaExceptions)(nil),           // 11: typedb.protocol.Transaction.GetSchemaExceptions
	(*Transaction_SchemaException)(nil),               // 12: typedb.protocol.Transaction.SchemaException
	(*Transaction_StreamSignal)(nil),                  // 13: typedb.protocol.Transaction.StreamSignal
	nil,                                               // 14: typedb.protocol.Transaction.Req.MetadataEntry
	(*Transaction_Open_Req)(nil),                      // 15: typedb.protocol.Transaction.Open.Req
	(*Transaction_Open_Res)(nil),                      // 16: typedb.protocol.Transaction.Open.Res
	(*Transaction_Commit_Req)(nil),                    // 17: typedb.protocol.Transaction.Commit.Req
	(*Transaction_Commit_Res)(nil),                    // 18: typedb.protocol.Transaction.Commit.Res
	(*Transaction_Rollback_Req)(nil),                  // 19: typedb.protocol.Transaction.Rollback.Req
	(*Transaction_Rollback_Res)(nil),                  // 20: typedb.protocol.Transaction.Rollback.Res
	(*Transaction_Close_Req)(nil),                     // 21: typedb.protocol.Transaction.Close.Req
	(*Transaction_Close_Res)(nil),                     // 22: typedb.protocol.Transaction.Close.Res
	(*Transaction_GetSchemaExceptions_Req)(nil),       // 23: typedb.protocol.Transaction.GetSchemaExceptions.Req
	(*Transaction_GetSchemaExceptions_Res)(nil),       // 24: typedb.protocol.Transaction.GetSchemaExceptions.Res
	(*Transaction_StreamSignal_Req)(nil),              // 25: typedb.protocol.Transaction.StreamSignal.Req
	(*Transaction_StreamSignal_ResPart)(nil),          // 26: typedb.protocol.Transaction.StreamSignal.ResPart
	(*Transaction_StreamSignal_ResPart_Continue)(nil), // 27: typedb.protocol.Transaction.StreamSignal.ResPart.Continue
	(*Transaction_StreamSignal_ResPart_Done)(nil),     // 28: typedb.protocol.Transaction.StreamSignal.ResPart.Done
	(*Query_Req)(nil),                                 // 29: typedb.protocol.Query.Req
	(*Query_InitialRes)(nil),                          // 30: typedb.protocol.Query.InitialRes
	(*Query_ResPart)(nil),                             // 31: typedb.protocol.Query.ResPart
	(*Options_Transaction)(nil),                       // 32: typedb.protocol.Options.Transaction
	(*Error)(nil),                                     // 33: typedb.protocol.Error
}
var file_proto_transaction_proto_depIdxs = []int32{
	4,  // 0: typedb.protocol.Transaction.Client.reqs:type_name -> typedb.protocol.Transaction.Req
	5,  // 1: typedb.protocol.Transaction.Server.res:type_name -> typedb.protocol.Transaction.Res
	6,  // 2: typedb.protocol.Transaction.Server.res_part:type_name -> typedb.protocol.Transaction.ResPart
	14, // 3: typedb.protocol.Transaction.Req.metadata:type_name -> typedb.protocol.Transaction.Req.MetadataEntry
	15, // 4: typedb.protocol.Transaction.Req.open_req:type_name -> typedb.protocol.Transaction.Open.Req
	29, // 5: typedb.protocol.Transaction.Req.query_req:type_name -> typedb.protocol.Query.Req
	25, // 6: typedb.protocol.Transaction.Req.stream_req:type_name -> typedb.protocol.Transaction.StreamSignal.Req
	17, // 7: typedb.protocol.Transaction.Req.commit_req:type_name -> typedb.protocol.Transaction.Commit.Req
	19, // 8: typedb.protocol.Transaction.Req.rollback_req:type_name -> typedb.protocol.Transaction.Rollback.Req
	21, // 9: typedb.protocol.Transaction.Req.close_req:type_name -> typedb.protocol.Transaction.Close.Req
	16, // 10: typedb.protocol.Transaction.Res.open_res:type_name -> typedb.protocol.Transaction.Open.Res
	30, // 11: typedb.protocol.Transaction.Res.query_initial_res:type_name -> typedb.protocol.Query.InitialRes
	18, // 12: typedb.protocol.Transaction.Res.commit_res:type_name -> typedb.protocol.Transaction.Commit.Res
	20, // 13: typedb.protocol.Transaction.Res.rollback_res:type_name -> typedb.protocol.Transaction.Rollback.Res
	31, // 14: typedb.protocol.Transaction.ResPart.query_res:type_name -> typedb.protocol.Query.ResPart
	26, // 15: typedb.protocol.Transaction.ResPart.stream_res:type_name -> typedb.protocol.Transaction.StreamSignal.ResPart
	0,  // 16: typedb.protocol.Transaction.Open.Req.type:type_name -> typedb.protocol.Transaction.Type
	32, // 17: typedb.protocol.Transaction.Open.Req.options:type_name -> typedb.protocol.Options.Transaction
	12, // 18: typedb.protocol.Transaction.GetSchemaExceptions.Res.exceptions:type_name -> typedb.protocol.Transaction.SchemaException
	27, // 19: typedb.protocol.Transaction.StreamSignal.ResPart.continue:type_name -> typedb.protocol.Transaction.StreamSignal.ResPart.Continue
	28, // 20: typedb.protocol.Transaction.StreamSignal.ResPart.done:type_name -> typedb.protocol.Transaction.StreamSignal.ResPart.Done
	33, // 21: typedb.protocol.Transaction.StreamSignal.ResPart.error:type_name -> typedb.protocol.Error
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_transaction_proto_init() }
func file_proto_transaction_proto_init() {
	if File_proto_transaction_proto != nil {
		return
	}
	file_proto_error_proto_init()
	file_proto_options_proto_init()
	file_proto_query_proto_init()
	file_proto_transaction_proto_msgTypes[2].OneofWrappers = []any{
		(*Transaction_Server_Res)(nil),
		(*Transaction_Server_ResPart)(nil),
	}
	file_proto_transaction_proto_msgTypes[3].OneofWrappers = []any{
		(*Transaction_Req_OpenReq)(nil),
		(*Transaction_Req_QueryReq)(nil),
		(*Transaction_Req_StreamReq)(nil),
		(*Transaction_Req_CommitReq)(nil),
		(*Transaction_Req_RollbackReq)(nil),
		(*Transaction_Req_CloseReq)(nil),
	}
	file_proto_transaction_proto_msgTypes[4].OneofWrappers = []any{
		(*Transaction_Res_OpenRes)(nil),
		(*Transaction_Res_QueryInitialRes)(nil),
		(*Transaction_Res_CommitRes)(nil),
		(*Transaction_Res_RollbackRes)(nil),
	}
	file_proto_transaction_proto_msgTypes[5].OneofWrappers = []any{
		(*Transaction_ResPart_QueryRes)(nil),
		(*Transaction_ResPart_StreamRes)(nil),
	}
	file_proto_transaction_proto_msgTypes[25].OneofWrappers = []any{
		(*Transaction_StreamSignal_ResPart_Continue_)(nil),
		(*Transaction_StreamSignal_ResPart_Done_)(nil),
		(*Transaction_StreamSignal_ResPart_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_proto_depIdxs,
		EnumInfos:         file_proto_transaction_proto_enumTypes,
		MessageInfos:      file_proto_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_proto = out.File
	file_proto_transaction_proto_goTypes = nil
	file_proto_transaction_proto_depIdxs = nil
}
