// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserManager struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager) Reset() {
	*x = UserManager{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager) ProtoMessage() {}

func (x *UserManager) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager.ProtoReflect.Descriptor instead.
func (*UserManager) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type UserManager_All struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_All) Reset() {
	*x = UserManager_All{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_All) ProtoMessage() {}

func (x *UserManager_All) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_All.ProtoReflect.Descriptor instead.
func (*UserManager_All) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 0}
}

type UserManager_Contains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Contains) Reset() {
	*x = UserManager_Contains{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Contains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Contains) ProtoMessage() {}

func (x *UserManager_Contains) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Contains.ProtoReflect.Descriptor instead.
func (*UserManager_Contains) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 1}
}

type UserManager_Get struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Get) Reset() {
	*x = UserManager_Get{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Get) ProtoMessage() {}

func (x *UserManager_Get) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Get.ProtoReflect.Descriptor instead.
func (*UserManager_Get) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 2}
}

type UserManager_Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Create) Reset() {
	*x = UserManager_Create{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Create) ProtoMessage() {}

func (x *UserManager_Create) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Create.ProtoReflect.Descriptor instead.
func (*UserManager_Create) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 3}
}

type UserManager_All_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_All_Req) Reset() {
	*x = UserManager_All_Req{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_All_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_All_Req) ProtoMessage() {}

func (x *UserManager_All_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_All_Req.ProtoReflect.Descriptor instead.
func (*UserManager_All_Req) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 0, 0}
}

type UserManager_All_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_All_Res) Reset() {
	*x = UserManager_All_Res{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_All_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_All_Res) ProtoMessage() {}

func (x *UserManager_All_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_All_Res.ProtoReflect.Descriptor instead.
func (*UserManager_All_Res) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *UserManager_All_Res) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserManager_Contains_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Contains_Req) Reset() {
	*x = UserManager_Contains_Req{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Contains_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Contains_Req) ProtoMessage() {}

func (x *UserManager_Contains_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Contains_Req.ProtoReflect.Descriptor instead.
func (*UserManager_Contains_Req) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *UserManager_Contains_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserManager_Contains_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contains      bool                   `protobuf:"varint,1,opt,name=contains,proto3" json:"contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Contains_Res) Reset() {
	*x = UserManager_Contains_Res{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Contains_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Contains_Res) ProtoMessage() {}

func (x *UserManager_Contains_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Contains_Res.ProtoReflect.Descriptor instead.
func (*UserManager_Contains_Res) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *UserManager_Contains_Res) GetContains() bool {
	if x != nil {
		return x.Contains
	}
	return false
}

type UserManager_Get_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Get_Req) Reset() {
	*x = UserManager_Get_Req{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Get_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Get_Req) ProtoMessage() {}

func (x *UserManager_Get_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Get_Req.ProtoReflect.Descriptor instead.
func (*UserManager_Get_Req) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *UserManager_Get_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserManager_Get_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Get_Res) Reset() {
	*x = UserManager_Get_Res{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Get_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Get_Res) ProtoMessage() {}

func (x *UserManager_Get_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Get_Res.ProtoReflect.Descriptor instead.
func (*UserManager_Get_Res) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *UserManager_Get_Res) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserManager_Create_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Create_Req) Reset() {
	*x = UserManager_Create_Req{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Create_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Create_Req) ProtoMessage() {}

func (x *UserManager_Create_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Create_Req.ProtoReflect.Descriptor instead.
func (*UserManager_Create_Req) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *UserManager_Create_Req) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserManager_Create_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserManager_Create_Res) Reset() {
	*x = UserManager_Create_Res{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserManager_Create_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManager_Create_Res) ProtoMessage() {}

func (x *UserManager_Create_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManager_Create_Res.ProtoReflect.Descriptor instead.
func (*UserManager_Create_Res) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0, 3, 1}
}

type User_Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Update) Reset() {
	*x = User_Update{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Update) ProtoMessage() {}

func (x *User_Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Update.ProtoReflect.Descriptor instead.
func (*User_Update) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1, 0}
}

type User_Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Delete) Reset() {
	*x = User_Delete{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Delete) ProtoMessage() {}

func (x *User_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Delete.ProtoReflect.Descriptor instead.
func (*User_Delete) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1, 1}
}

type User_Update_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Update_Req) Reset() {
	*x = User_Update_Req{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Update_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Update_Req) ProtoMessage() {}

func (x *User_Update_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Update_Req.ProtoReflect.Descriptor instead.
func (*User_Update_Req) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *User_Update_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User_Update_Req) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User_Update_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Update_Res) Reset() {
	*x = User_Update_Res{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Update_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Update_Res) ProtoMessage() {}

func (x *User_Update_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Update_Res.ProtoReflect.Descriptor instead.
func (*User_Update_Res) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1, 0, 1}
}

type User_Delete_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Delete_Req) Reset() {
	*x = User_Delete_Req{}
	mi := &file_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Delete_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Delete_Req) ProtoMessage() {}

func (x *User_Delete_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Delete_Req.ProtoReflect.Descriptor instead.
func (*User_Delete_Req) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *User_Delete_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User_Delete_Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Delete_Res) Reset() {
	*x = User_Delete_Res{}
	mi := &file_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Delete_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Delete_Res) ProtoMessage() {}

func (x *User_Delete_Res) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Delete_Res.ProtoReflect.Descriptor instead.
func (*User_Delete_Res) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1, 1, 1}
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x0ftypedb.protocol\"\xb0\x02\n" +
	"\vUserManager\x1a@\n" +
	"\x03All\x1a\x05\n" +
	"\x03Req\x1a2\n" +
	"\x03Res\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.typedb.protocol.UserR\x05users\x1aH\n" +
	"\bContains\x1a\x19\n" +
	"\x03Req\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a!\n" +
	"\x03Res\x12\x1a\n" +
	"\bcontains\x18\x01 \x01(\bR\bcontains\x1aR\n" +
	"\x03Get\x1a\x19\n" +
	"\x03Req\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a0\n" +
	"\x03Res\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.typedb.protocol.UserR\x04user\x1aA\n" +
	"\x06Create\x1a0\n" +
	"\x03Req\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.typedb.protocol.UserR\x04user\x1a\x05\n" +
	"\x03Res\"\xcb\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01\x1aU\n" +
	"\x06Update\x1aD\n" +
	"\x03Req\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.typedb.protocol.UserR\x04user\x1a\x05\n" +
	"\x03Res\x1a*\n" +
	"\x06Delete\x1a\x19\n" +
	"\x03Req\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\x05\n" +
	"\x03ResB\v\n" +
	"\t_passwordBCZAgithub.com/joycheney/go-typedb-v3-grpc/pbb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_user_proto_goTypes = []any{
	(*UserManager)(nil),              // 0: typedb.protocol.UserManager
	(*User)(nil),                     // 1: typedb.protocol.User
	(*UserManager_All)(nil),          // 2: typedb.protocol.UserManager.All
	(*UserManager_Contains)(nil),     // 3: typedb.protocol.UserManager.Contains
	(*UserManager_Get)(nil),          // 4: typedb.protocol.UserManager.Get
	(*UserManager_Create)(nil),       // 5: typedb.protocol.UserManager.Create
	(*UserManager_All_Req)(nil),      // 6: typedb.protocol.UserManager.All.Req
	(*UserManager_All_Res)(nil),      // 7: typedb.protocol.UserManager.All.Res
	(*UserManager_Contains_Req)(nil), // 8: typedb.protocol.UserManager.Contains.Req
	(*UserManager_Contains_Res)(nil), // 9: typedb.protocol.UserManager.Contains.Res
	(*UserManager_Get_Req)(nil),      // 10: typedb.protocol.UserManager.Get.Req
	(*UserManager_Get_Res)(nil),      // 11: typedb.protocol.UserManager.Get.Res
	(*UserManager_Create_Req)(nil),   // 12: typedb.protocol.UserManager.Create.Req
	(*UserManager_Create_Res)(nil),   // 13: typedb.protocol.UserManager.Create.Res
	(*User_Update)(nil),              // 14: typedb.protocol.User.Update
	(*User_Delete)(nil),              // 15: typedb.protocol.User.Delete
	(*User_Update_Req)(nil),          // 16: typedb.protocol.User.Update.Req
	(*User_Update_Res)(nil),          // 17: typedb.protocol.User.Update.Res
	(*User_Delete_Req)(nil),          // 18: typedb.protocol.User.Delete.Req
	(*User_Delete_Res)(nil),          // 19: typedb.protocol.User.Delete.Res
}
var file_proto_user_proto_depIdxs = []int32{
	1, // 0: typedb.protocol.UserManager.All.Res.users:type_name -> typedb.protocol.User
	1, // 1: typedb.protocol.UserManager.Get.Res.user:type_name -> typedb.protocol.User
	1, // 2: typedb.protocol.UserManager.Create.Req.user:type_name -> typedb.protocol.User
	1, // 3: typedb.protocol.User.Update.Req.user:type_name -> typedb.protocol.User
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	file_proto_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
