// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/version.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version int32

const (
	Version_UNSPECIFIED Version = 0
	Version_VERSION     Version = 7
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "UNSPECIFIED",
		7: "VERSION",
	}
	Version_value = map[string]int32{
		"UNSPECIFIED": 0,
		"VERSION":     7,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_version_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_proto_version_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_proto_version_proto_rawDescGZIP(), []int{0}
}

var File_proto_version_proto protoreflect.FileDescriptor

const file_proto_version_proto_rawDesc = "" +
	"\n" +
	"\x13proto/version.proto\x12\x0ftypedb.protocol*K\n" +
	"\aVersion\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aVERSION\x10\a\"\x04\b\x01\x10\x01\"\x04\b\x02\x10\x02\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04\"\x04\b\x05\x10\x05\"\x04\b\x06\x10\x06BCZAgithub.com/mcp-software-think-execute-server/go-typedb-v3-grpc/pbb\x06proto3"

var (
	file_proto_version_proto_rawDescOnce sync.Once
	file_proto_version_proto_rawDescData []byte
)

func file_proto_version_proto_rawDescGZIP() []byte {
	file_proto_version_proto_rawDescOnce.Do(func() {
		file_proto_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_version_proto_rawDesc), len(file_proto_version_proto_rawDesc)))
	})
	return file_proto_version_proto_rawDescData
}

var file_proto_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_version_proto_goTypes = []any{
	(Version)(0), // 0: typedb.protocol.Version
}
var file_proto_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_version_proto_init() }
func file_proto_version_proto_init() {
	if File_proto_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_version_proto_rawDesc), len(file_proto_version_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_version_proto_goTypes,
		DependencyIndexes: file_proto_version_proto_depIdxs,
		EnumInfos:         file_proto_version_proto_enumTypes,
	}.Build()
	File_proto_version_proto = out.File
	file_proto_version_proto_goTypes = nil
	file_proto_version_proto_depIdxs = nil
}
